// Code generated by `aru view:build` from home.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package views

import (
	"html/template"
	"io"

	"github.com/arandu-io/framework/view"
)

//line resources/views/home.kyse.go:5

// HomeData is what HomeController.Index hands this page.
//
// A struct, never a map. That is what turns a typo in a field name into a
// compile error instead of a blank space on a page that answered 200.
//
// The embedded view.Page is the chrome the layout draws -- the title, the
// description, the token and the navigation -- and embedding it is all this
// page has to do to fit the frame.
type HomeData struct {
	view.Page

	// Name is who the page greets.
	Name string
	// Features is what the landing page lists.
	Features []Feature
}

// Feature is one entry of the list below.
type Feature struct {
	Title string
	Body  string
}

//line resources/views/home.go:40

func init() { view.Register("home", renderHome) }

// renderHome renders home.
func renderHome(w io.Writer, data any) error {
	d, ok := data.(HomeData)
	if !ok {
		return view.WrongData("home", "HomeData", data)
	}
	_ = d
	sections := map[string]func(io.Writer) error{
		"content": func(w io.Writer) error {
			var err error
			if err == nil {
				_, err = io.WriteString(w, "\t<h1 class=\"text-3xl font-semibold tracking-tight sm:text-4xl\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\tHello ")
			}
			if err == nil {
//line resources/views/home.kyse.go:34
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Name)))
//line resources/views/home.go:63
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</h1>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t<p class=\"text-muted-foreground mt-4 text-base\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\tIt is not the developer who guarantees the architecture. It is the compiler.\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</p>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
//line resources/views/home.kyse.go:40
			if len(d.Features) > 0 {
//line resources/views/home.go:85
				if err == nil {
					_, err = io.WriteString(w, "\t\t<ul class=\"mt-10 grid gap-4 sm:grid-cols-2\">\n")
				}
//line resources/views/home.kyse.go:42
				for _, feature := range d.Features {
					_ = feature
//line resources/views/home.go:92
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t<li class=\"card p-5\">\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t<h2 class=\"text-sm font-semibold\">")
					}
					if err == nil {
//line resources/views/home.kyse.go:44
						_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(feature.Title)))
//line resources/views/home.go:102
					}
					if err == nil {
						_, err = io.WriteString(w, "</h2>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t<p class=\"text-muted-foreground mt-1 text-sm\">")
					}
					if err == nil {
//line resources/views/home.kyse.go:45
						_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(feature.Body)))
//line resources/views/home.go:113
					}
					if err == nil {
						_, err = io.WriteString(w, "</p>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t</li>\n")
					}
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t</ul>\n")
				}
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			return err
		},
	}
	return view.RenderInto(w, "layouts.app", data, sections)
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
)
