// Code generated by `aru view:build` from home.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package views

import (
	"html/template"
	"io"

	"github.com/arandu-io/framework/view"
)

// HomeData is what HomeController.Index hands this page.
//
// A struct, never a map. That is what turns a typo in a field name into a
// compile error instead of a blank space on a page that answered 200.
//
// The embedded Page is the state the layout draws -- the title, the brand, the
// token and the navigation. This struct declares only what this page shows, and
// satisfies the layout's contract by embedding.
type HomeData struct {
	Page

	// Name is who the page greets.
	Name string
	// Features is what the landing page lists.
	Features []Feature
}

// Feature is one entry of the list below.
type Feature struct {
	Title string
	Body  string
}

// Compile-time proof that this page fits the layout it extends.
var _ Layout = HomeData{}

func init() { view.Register("home", renderHome) }

// renderHome renders home.
func renderHome(w io.Writer, data any) error {
	d, ok := data.(HomeData)
	if !ok {
		return view.WrongData("home", "HomeData", data)
	}
	_ = d
	sections := map[string]func(io.Writer) error{
		"content": func(w io.Writer) error {
			var err error
			if err == nil {
				_, err = io.WriteString(w, "\t<h1 class=\"text-3xl font-semibold tracking-tight sm:text-4xl\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\tHello ")
			}
			if err == nil {
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.Name)))
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</h1>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t<p class=\"mt-4 text-base text-slate-600 dark:text-slate-300\">\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t\tIt is not the developer who guarantees the architecture. It is the compiler.\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\t</p>\n")
			}
			if err == nil {
				_, err = io.WriteString(w, "\n")
			}
			if len(d.Features) > 0 {
				if err == nil {
					_, err = io.WriteString(w, "\t\t<ul class=\"mt-10 grid gap-4 sm:grid-cols-2\">\n")
				}
				for _, feature := range d.Features {
					_ = feature
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t<li class=\"rounded-lg border border-slate-200 p-5 dark:border-slate-800\">\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t<h2 class=\"text-sm font-semibold\">")
					}
					if err == nil {
						_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(feature.Title)))
					}
					if err == nil {
						_, err = io.WriteString(w, "</h2>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t\t<p class=\"mt-1 text-sm text-slate-600 dark:text-slate-300\">")
					}
					if err == nil {
						_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(feature.Body)))
					}
					if err == nil {
						_, err = io.WriteString(w, "</p>\n")
					}
					if err == nil {
						_, err = io.WriteString(w, "\t\t\t\t</li>\n")
					}
				}
				if err == nil {
					_, err = io.WriteString(w, "\t\t</ul>\n")
				}
			}
			return err
		},
	}
	return view.RenderInto(w, "layouts.app", data, sections)
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
)
