// Code generated by `aru view:build` from app.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package views

import (
	"html/template"
	"io"

	"github.com/arandu-io/framework/view"
)

// Layout is what every page hands the application layout.
//
// An interface rather than a struct, so each page keeps its own typed data and
// still fits the frame: one struct per page, one layout, no map anywhere (RULE
// 9). A page that forgets PageTitle does not compile.
type Layout interface {
	// PageTitle is what the browser tab shows.
	PageTitle() string
}

func init() { view.RegisterLayout("layouts.app", renderLayoutsApp) }

// renderLayoutsApp renders the layouts.app layout.
func renderLayoutsApp(w io.Writer, data any, sections map[string]func(io.Writer) error) error {
	d, ok := data.(Layout)
	if !ok {
		return view.WrongData("layouts.app", "Layout", data)
	}
	_ = d
	var err error
	if err == nil {
		_, err = io.WriteString(w, "<!doctype html>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<html lang=\"en\" class=\"h-full\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<head>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<meta charset=\"utf-8\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<title>")
	}
	if err == nil {
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.PageTitle())))
	}
	if err == nil {
		_, err = io.WriteString(w, "</title>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<link rel=\"icon\" href=\"/favicon.ico\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<!-- Every asset is embedded in the binary and addressed by content hash. No\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t     CDN, because the CSP is script-src 'self'; no build directory, because\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t     there is no bundler to write one (RULE 13). -->\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<link rel=\"stylesheet\" href=\"")
	}
	if err == nil {
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(view.URL("app.css"))))
	}
	if err == nil {
		_, err = io.WriteString(w, "\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<script src=\"")
	}
	if err == nil {
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(view.URL("htmx.min.js"))))
	}
	if err == nil {
		_, err = io.WriteString(w, "\" defer></script>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<script src=\"")
	}
	if err == nil {
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(view.URL("alpine.min.js"))))
	}
	if err == nil {
		_, err = io.WriteString(w, "\" defer></script>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "</head>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<body class=\"h-full bg-white text-slate-900 antialiased dark:bg-slate-950 dark:text-slate-100\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<div class=\"mx-auto flex min-h-full w-full max-w-3xl flex-col px-6\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t<header class=\"flex items-center justify-between border-b border-slate-200 py-6 dark:border-slate-800\">\n")
	}
	if err == nil {
		err = view.Yield(w, sections, "header")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t</header>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t<main class=\"flex-1 py-12\">\n")
	}
	if err == nil {
		err = view.Yield(w, sections, "content")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t</main>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t<footer class=\"border-t border-slate-200 py-6 text-sm text-slate-500 dark:border-slate-800 dark:text-slate-400\">\n")
	}
	if err == nil {
		err = view.Yield(w, sections, "footer")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t</footer>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t</div>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "</body>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "</html>\n")
	}
	return err
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
)
