// Example resource. Remove with the list under "The example resource" in README.md.

package migrations

import (
	"context"

	"github.com/arandu-io/hesape/database/migrations"
	"github.com/arandu-io/hesape/database/schema"
)

// CreateCommentsTable creates the comments table.
//
// The init below registers it, so nothing lists it and no list can fall out of
// date. What still has to be true is that this package reaches the binary: Go
// leaves out a package nobody imports, and an init that is not linked never
// runs.
//
// A migration is immutable once published. Changing this one changes nothing on
// a database that already applied it, and leaves two schemas in the world under
// one name -- alter it with a new migration instead.
//
// The column types are the Blueprint's to spell, one per engine. That used to be
// written out here, with a comment explaining that anything a key names is
// VARCHAR rather than TEXT because MySQL refuses TEXT in a key without a prefix
// length -- which is the grammar's job, done by hand in every migration.
//
// The id is generated by the application: gen_random_uuid, UUID() and randomblob
// are three spellings of one idea, and depending on any of them ties the schema
// to one engine.
type CreateCommentsTable struct{ migrations.BaseMigration }

func init() { migrations.Register(CreateCommentsTable{}) }

// GetName is the migration's identity, and its order. It is immutable: this
// string is what the applied-migrations table records.
func (CreateCommentsTable) GetName() string { return "2026_10_09_000001_create_comments_table" }

// Up creates the table and the index every listing reads through.
//
// The Blueprint chooses the column type per engine, which is the whole reason it
// exists: VARCHAR here and TEXT there is not a preference, it is that MySQL
// refuses TEXT in a key without a prefix length. Writing the type by hand meant
// getting that right in every migration, and a comment explaining it in each.
//
// conn.Statement is still there for what no Blueprint reaches -- an extension, a
// CREATE INDEX CONCURRENTLY, a backfill that reads before it writes.
func (CreateCommentsTable) Up(ctx context.Context, conn migrations.Connection) error {
	return conn.Schema().Create(ctx, "comments", func(table *schema.Blueprint) {
		table.String("id").Primary()
		table.String("tenant_id")
		// The note's key is text, as notes.id is, so the column holds it on
		// every engine the project may move to.
		table.String("note_id")
		table.String("user_id")
		table.Text("body")
		table.Timestamps()

		// The index every listing reads through: one note's comments inside a
		// tenant, the sort column next, then the key, so that a page boundary is
		// a single comparison rather than a scan of everything the sort ties.
		table.Index([]string{"tenant_id", "note_id", "created_at", "id"})
	})
}

// Down drops the table, and the index with it.
func (CreateCommentsTable) Down(ctx context.Context, conn migrations.Connection) error {
	return conn.Schema().DropIfExists(ctx, "comments")
}
