// Code generated by aru model:build from Comment.go. DO NOT EDIT.

package models

import (
	"context"
	"iter"

	"github.com/arandu-io/hesape/auth"
	"github.com/arandu-io/hesape/database/model"
	"github.com/arandu-io/hesape/database/query"
	"github.com/arandu-io/hesape/pagination"
)

// Comments starts a query on the table of Comment, through db.
//
// Global scopes are on and, unless the table is Global, every statement is
// filtered by the tenant of the Grant its terminal takes.
func Comments(db model.DB) *CommentQuery { return &CommentQuery{b: commentTable.Query(db)} }

// CommentQuery is a query on the table of Comment.
//
// The methods that build return the query, so they chain. The methods that run
// take a context and an auth.Grant, and return Comment rows or a value; there is
// no way to run one without a Grant.
type CommentQuery struct{ b *model.Builder }

// Base returns the core builder the query forwards to. It is for code in this
// package -- a local scope in the custom block of Comment.go -- and for the
// factory, which builds rows through it.
func (q *CommentQuery) Base() *model.Builder { return q.b }

// New returns an empty Comment on the query's connection, not yet saved, filled
// with what WithAttributes recorded on the query.
func (q *CommentQuery) New() (*Comment, error) {
	e, err := q.b.NewModelInstance(nil)
	return commentOf(e), err
}

// CommentCollection is rows of Comment, as a query returns them.
type CommentCollection []*Comment

// CommentCollectionOf converts rows of the table of Comment. A nil input is a nil
// collection.
func CommentCollectionOf(rows model.Rows) CommentCollection {
	if rows == nil {
		return nil
	}
	out := make(CommentCollection, len(rows))
	for i, e := range rows {
		out[i] = e.(*Comment)
	}
	return out
}

func commentOf(e model.Entity) *Comment {
	row, _ := e.(*Comment)
	return row
}

// commentColumn turns a closure over CommentQuery into one over the core builder, so
// passing func(*CommentQuery) where a column goes adds a parenthesised group.
func commentColumn(column any) any {
	if group, ok := column.(func(*CommentQuery)); ok {
		return func(b *model.Builder) { group(&CommentQuery{b: b}) }
	}
	return column
}

// Clone returns an independent copy of the query.
func (q *CommentQuery) Clone() *CommentQuery { return &CommentQuery{b: q.b.Clone()} }

// Where adds a where clause; a func(*CommentQuery) in place of the column adds a group.
func (q *CommentQuery) Where(column any, args ...any) *CommentQuery {
	q.b.Where(commentColumn(column), args...)
	return q
}

// OrWhere adds an or-where clause; a func(*CommentQuery) in place of the column adds a group.
func (q *CommentQuery) OrWhere(column any, args ...any) *CommentQuery {
	q.b.OrWhere(commentColumn(column), args...)
	return q
}

// WhereNot adds a negated where clause, or a negated group.
func (q *CommentQuery) WhereNot(column any, args ...any) *CommentQuery {
	q.b.WhereNot(commentColumn(column), args...)
	return q
}

// OrWhereNot adds an or-joined negated where clause, or a negated group.
func (q *CommentQuery) OrWhereNot(column any, args ...any) *CommentQuery {
	q.b.OrWhereNot(commentColumn(column), args...)
	return q
}

func (q *CommentQuery) WhereIn(column any, values []any) *CommentQuery {
	q.b.WhereIn(column, values)
	return q
}

func (q *CommentQuery) WhereNotIn(column any, values []any) *CommentQuery {
	q.b.WhereNotIn(column, values)
	return q
}

func (q *CommentQuery) WhereNull(columns ...any) *CommentQuery {
	q.b.WhereNull(columns...)
	return q
}

func (q *CommentQuery) WhereNotNull(columns ...any) *CommentQuery {
	q.b.WhereNotNull(columns...)
	return q
}

func (q *CommentQuery) WhereBetween(column any, from, to any) *CommentQuery {
	q.b.WhereBetween(column, from, to)
	return q
}

func (q *CommentQuery) WhereColumn(first any, args ...any) *CommentQuery {
	q.b.WhereColumn(first, args...)
	return q
}

func (q *CommentQuery) WhereKey(id any) *CommentQuery {
	q.b.WhereKey(id)
	return q
}

func (q *CommentQuery) WhereExists(callback func(*query.Builder)) *CommentQuery {
	q.b.WhereExists(callback)
	return q
}

func (q *CommentQuery) WhereNotExists(callback func(*query.Builder)) *CommentQuery {
	q.b.WhereNotExists(callback)
	return q
}

func (q *CommentQuery) WhereHas(relation string, callback func(*query.Builder)) *CommentQuery {
	q.b.WhereHas(relation, callback)
	return q
}

func (q *CommentQuery) OrWhereHas(relation string, callback func(*query.Builder)) *CommentQuery {
	q.b.OrWhereHas(relation, callback)
	return q
}

func (q *CommentQuery) WhereDoesntHave(relation string, callback func(*query.Builder)) *CommentQuery {
	q.b.WhereDoesntHave(relation, callback)
	return q
}

func (q *CommentQuery) OrWhereDoesntHave(relation string, callback func(*query.Builder)) *CommentQuery {
	q.b.OrWhereDoesntHave(relation, callback)
	return q
}

func (q *CommentQuery) WhereRelation(relation string, column any, args ...any) *CommentQuery {
	q.b.WhereRelation(relation, column, args...)
	return q
}

func (q *CommentQuery) OrWhereRelation(relation string, column any, args ...any) *CommentQuery {
	q.b.OrWhereRelation(relation, column, args...)
	return q
}

func (q *CommentQuery) WhereHasCount(relation string, callback func(*query.Builder), operator string, count int) *CommentQuery {
	q.b.WhereHasCount(relation, callback, operator, count)
	return q
}

func (q *CommentQuery) WhereBelongsTo(relationshipName string, related ...model.Entity) *CommentQuery {
	q.b.WhereBelongsTo(relationshipName, related...)
	return q
}

func (q *CommentQuery) Has(relation, operator string, count int, boolean string, callback func(*query.Builder)) *CommentQuery {
	q.b.Has(relation, operator, count, boolean, callback)
	return q
}

func (q *CommentQuery) OrHas(relation, operator string, count int) *CommentQuery {
	q.b.OrHas(relation, operator, count)
	return q
}

func (q *CommentQuery) DoesntHave(relation, boolean string, callback func(*query.Builder)) *CommentQuery {
	q.b.DoesntHave(relation, boolean, callback)
	return q
}

func (q *CommentQuery) OrDoesntHave(relation string) *CommentQuery {
	q.b.OrDoesntHave(relation)
	return q
}

func (q *CommentQuery) Select(columns ...any) *CommentQuery {
	q.b.Select(columns...)
	return q
}

func (q *CommentQuery) AddSelect(columns ...any) *CommentQuery {
	q.b.AddSelect(columns...)
	return q
}

func (q *CommentQuery) SelectRaw(expression string, bindings ...any) *CommentQuery {
	q.b.SelectRaw(expression, bindings...)
	return q
}

func (q *CommentQuery) Join(table any, first any, args ...any) *CommentQuery {
	q.b.Join(table, first, args...)
	return q
}

func (q *CommentQuery) GroupBy(groups ...any) *CommentQuery {
	q.b.GroupBy(groups...)
	return q
}

func (q *CommentQuery) OrderBy(column any, direction ...string) *CommentQuery {
	q.b.OrderBy(column, direction...)
	return q
}

func (q *CommentQuery) OrderByDesc(column any) *CommentQuery {
	q.b.OrderByDesc(column)
	return q
}

func (q *CommentQuery) Latest(column ...string) *CommentQuery {
	q.b.Latest(column...)
	return q
}

func (q *CommentQuery) Oldest(column ...string) *CommentQuery {
	q.b.Oldest(column...)
	return q
}

func (q *CommentQuery) Limit(value int) *CommentQuery {
	q.b.Limit(value)
	return q
}

func (q *CommentQuery) Offset(value int) *CommentQuery {
	q.b.Offset(value)
	return q
}

func (q *CommentQuery) ForPage(page, perPage int) *CommentQuery {
	q.b.ForPage(page, perPage)
	return q
}

func (q *CommentQuery) With(relations ...string) *CommentQuery {
	q.b.With(relations...)
	return q
}

func (q *CommentQuery) WithCount(relations ...string) *CommentQuery {
	q.b.WithCount(relations...)
	return q
}

func (q *CommentQuery) WithExists(relation string) *CommentQuery {
	q.b.WithExists(relation)
	return q
}

func (q *CommentQuery) WithSum(relation, column string) *CommentQuery {
	q.b.WithSum(relation, column)
	return q
}

func (q *CommentQuery) WithAvg(relation, column string) *CommentQuery {
	q.b.WithAvg(relation, column)
	return q
}

func (q *CommentQuery) WithMin(relation, column string) *CommentQuery {
	q.b.WithMin(relation, column)
	return q
}

func (q *CommentQuery) WithMax(relation, column string) *CommentQuery {
	q.b.WithMax(relation, column)
	return q
}

func (q *CommentQuery) Without(relations ...string) *CommentQuery {
	q.b.Without(relations...)
	return q
}

func (q *CommentQuery) WithoutGlobalScope(identifier string) *CommentQuery {
	q.b.WithoutGlobalScope(identifier)
	return q
}

func (q *CommentQuery) WithoutGlobalScopes(identifiers ...string) *CommentQuery {
	q.b.WithoutGlobalScopes(identifiers...)
	return q
}

// Get runs the query and returns the rows.
func (q *CommentQuery) Get(ctx context.Context, g auth.Grant, columns ...any) (CommentCollection, error) {
	rows, err := q.b.Get(ctx, g, columns...)
	return CommentCollectionOf(rows), err
}

// First returns the first row, or nil and no error when there is none.
func (q *CommentQuery) First(ctx context.Context, g auth.Grant, columns ...any) (*Comment, error) {
	e, err := q.b.First(ctx, g, columns...)
	return commentOf(e), err
}

func (q *CommentQuery) FirstOrFail(ctx context.Context, g auth.Grant, columns ...any) (*Comment, error) {
	e, err := q.b.FirstOrFail(ctx, g, columns...)
	return commentOf(e), err
}

func (q *CommentQuery) FirstWhere(ctx context.Context, g auth.Grant, column any, args ...any) (*Comment, error) {
	e, err := q.b.FirstWhere(ctx, g, column, args...)
	return commentOf(e), err
}

func (q *CommentQuery) FirstOrNew(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Comment, error) {
	e, err := q.b.FirstOrNew(ctx, g, attributes, values)
	return commentOf(e), err
}

func (q *CommentQuery) FirstOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Comment, error) {
	e, err := q.b.FirstOrCreate(ctx, g, attributes, values)
	return commentOf(e), err
}

func (q *CommentQuery) Find(ctx context.Context, g auth.Grant, id any, columns ...any) (*Comment, error) {
	e, err := q.b.Find(ctx, g, id, columns...)
	return commentOf(e), err
}

func (q *CommentQuery) FindOrFail(ctx context.Context, g auth.Grant, id any, columns ...any) (*Comment, error) {
	e, err := q.b.FindOrFail(ctx, g, id, columns...)
	return commentOf(e), err
}

func (q *CommentQuery) FindOrNew(ctx context.Context, g auth.Grant, id any, columns ...any) (*Comment, error) {
	e, err := q.b.FindOrNew(ctx, g, id, columns...)
	return commentOf(e), err
}

func (q *CommentQuery) FindMany(ctx context.Context, g auth.Grant, ids []any, columns ...any) (CommentCollection, error) {
	rows, err := q.b.FindMany(ctx, g, ids, columns...)
	return CommentCollectionOf(rows), err
}

func (q *CommentQuery) Sole(ctx context.Context, g auth.Grant, columns ...any) (*Comment, error) {
	e, err := q.b.Sole(ctx, g, columns...)
	return commentOf(e), err
}

func (q *CommentQuery) Create(ctx context.Context, g auth.Grant, attributes map[string]any) (*Comment, error) {
	e, err := q.b.Create(ctx, g, attributes)
	return commentOf(e), err
}

func (q *CommentQuery) ForceCreate(ctx context.Context, g auth.Grant, attributes map[string]any) (*Comment, error) {
	e, err := q.b.ForceCreate(ctx, g, attributes)
	return commentOf(e), err
}

func (q *CommentQuery) UpdateOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Comment, error) {
	e, err := q.b.UpdateOrCreate(ctx, g, attributes, values)
	return commentOf(e), err
}

func (q *CommentQuery) Paginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (CommentCollection, *pagination.LengthAwarePage, error) {
	rows, meta, err := q.b.Paginate(ctx, g, perPage, page, opts, columns...)
	return CommentCollectionOf(rows), meta, err
}

func (q *CommentQuery) SimplePaginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (CommentCollection, *pagination.Page, error) {
	rows, meta, err := q.b.SimplePaginate(ctx, g, perPage, page, opts, columns...)
	return CommentCollectionOf(rows), meta, err
}

func (q *CommentQuery) CursorPaginate(ctx context.Context, g auth.Grant, perPage int, cursor *pagination.Cursor, opts pagination.Options, columns ...any) (CommentCollection, *pagination.CursorPage, error) {
	rows, meta, err := q.b.CursorPaginate(ctx, g, perPage, cursor, opts, columns...)
	return CommentCollectionOf(rows), meta, err
}

func (q *CommentQuery) Chunk(ctx context.Context, g auth.Grant, count int, callback func(CommentCollection, int) (bool, error)) error {
	return q.b.Chunk(ctx, g, count, func(rows model.Rows, page int) (bool, error) {
		return callback(CommentCollectionOf(rows), page)
	})
}

func (q *CommentQuery) Each(ctx context.Context, g auth.Grant, count int, callback func(*Comment, int) (bool, error)) error {
	return q.b.Each(ctx, g, count, func(e model.Entity, index int) (bool, error) {
		return callback(commentOf(e), index)
	})
}

func (q *CommentQuery) Cursor(ctx context.Context, g auth.Grant) iter.Seq2[*Comment, error] {
	return func(yield func(*Comment, error) bool) {
		for e, err := range q.b.Cursor(ctx, g) {
			if !yield(commentOf(e), err) {
				return
			}
		}
	}
}

func (q *CommentQuery) Count(ctx context.Context, g auth.Grant, columns ...any) (int64, error) {
	return q.b.Count(ctx, g, columns...)
}

func (q *CommentQuery) Exists(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.Exists(ctx, g)
}

func (q *CommentQuery) DoesntExist(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.DoesntExist(ctx, g)
}

func (q *CommentQuery) Pluck(ctx context.Context, g auth.Grant, column string) ([]any, error) {
	return q.b.Pluck(ctx, g, column)
}

func (q *CommentQuery) Value(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.Value(ctx, g, column)
}

func (q *CommentQuery) ValueOrFail(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.ValueOrFail(ctx, g, column)
}

func (q *CommentQuery) SoleValue(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.SoleValue(ctx, g, column)
}

func (q *CommentQuery) Sum(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Sum(ctx, g, column)
}

func (q *CommentQuery) Avg(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Avg(ctx, g, column)
}

func (q *CommentQuery) Min(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Min(ctx, g, column)
}

func (q *CommentQuery) Max(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Max(ctx, g, column)
}

func (q *CommentQuery) Update(ctx context.Context, g auth.Grant, values map[string]any) (int64, error) {
	return q.b.Update(ctx, g, values)
}

func (q *CommentQuery) Delete(ctx context.Context, g auth.Grant) (int64, error) {
	return q.b.Delete(ctx, g)
}

func (q *CommentQuery) Increment(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Increment(ctx, g, column, amount, extra)
}

func (q *CommentQuery) Decrement(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Decrement(ctx, g, column, amount, extra)
}

func (q *CommentQuery) Insert(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.Insert(ctx, g, values...)
}

func (q *CommentQuery) InsertOrIgnore(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.InsertOrIgnore(ctx, g, values...)
}

func (q *CommentQuery) Upsert(ctx context.Context, g auth.Grant, values []map[string]any, uniqueBy, update []string) (int64, error) {
	return q.b.Upsert(ctx, g, values, uniqueBy, update)
}

func (q *CommentQuery) Touch(ctx context.Context, g auth.Grant, column ...string) (int64, error) {
	return q.b.Touch(ctx, g, column...)
}

// Rows converts the collection back to the core's rows.
func (c CommentCollection) Rows() model.Rows {
	out := make(model.Rows, len(c))
	for i, row := range c {
		out[i] = row
	}
	return out
}

func (c CommentCollection) ModelKeys() []any { return c.Rows().ModelKeys() }

func (c CommentCollection) Find(key any) *Comment { return commentOf(c.Rows().Find(key)) }

func (c CommentCollection) FindOrFail(key any) (*Comment, error) {
	e, err := c.Rows().FindOrFail(key)
	return commentOf(e), err
}

func (c CommentCollection) Contains(key any) bool { return c.Rows().Contains(key) }

func (c CommentCollection) Pluck(column string) []any { return c.Rows().Pluck(column) }

func (c CommentCollection) Only(keys ...any) CommentCollection {
	return CommentCollectionOf(c.Rows().Only(keys...))
}

func (c CommentCollection) Except(keys ...any) CommentCollection {
	return CommentCollectionOf(c.Rows().Except(keys...))
}

func (c CommentCollection) Unique() CommentCollection { return CommentCollectionOf(c.Rows().Unique()) }

func (c CommentCollection) Load(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().Load(ctx, g, relations...)
}

func (c CommentCollection) LoadMissing(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadMissing(ctx, g, relations...)
}

func (c CommentCollection) LoadCount(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadCount(ctx, g, relations...)
}

func (c CommentCollection) Fresh(ctx context.Context, g auth.Grant, with ...string) (CommentCollection, error) {
	rows, err := c.Rows().Fresh(ctx, g, with...)
	return CommentCollectionOf(rows), err
}

func (c CommentCollection) ToArray() []map[string]any { return c.Rows().ToArray() }

// Fresh reads the row again, as a new Comment; it shadows the untyped one the
// embedded model promotes.
func (row *Comment) Fresh(ctx context.Context, g auth.Grant, with ...string) (*Comment, error) {
	e, err := row.Model.Fresh(ctx, g, with...)
	return commentOf(e), err
}

// Replicate returns an unsaved copy of the row without its key; it shadows the
// untyped one the embedded model promotes.
func (row *Comment) Replicate(except ...string) (*Comment, error) {
	e, err := row.Model.Replicate(except...)
	return commentOf(e), err
}
