// Code generated by aru model:build from Note.go. DO NOT EDIT.

package models

import (
	"context"
	"iter"

	"github.com/arandu-io/hesape/auth"
	"github.com/arandu-io/hesape/database/model"
	"github.com/arandu-io/hesape/database/query"
	"github.com/arandu-io/hesape/pagination"
)

// Notes starts a query on the table of Note, through db.
//
// Global scopes are on and, unless the table is Global, every statement is
// filtered by the tenant of the Grant its terminal takes.
func Notes(db model.DB) *NoteQuery { return &NoteQuery{b: noteTable.Query(db)} }

// NoteQuery is a query on the table of Note.
//
// The methods that build return the query, so they chain. The methods that run
// take a context and an auth.Grant, and return Note rows or a value; there is
// no way to run one without a Grant.
type NoteQuery struct{ b *model.Builder }

// Base returns the core builder the query forwards to. It is for code in this
// package -- a local scope in the custom block of Note.go -- and for the
// factory, which builds rows through it.
func (q *NoteQuery) Base() *model.Builder { return q.b }

// New returns an empty Note on the query's connection, not yet saved, filled
// with what WithAttributes recorded on the query.
func (q *NoteQuery) New() (*Note, error) {
	e, err := q.b.NewModelInstance(nil)
	return noteOf(e), err
}

// NoteCollection is rows of Note, as a query returns them.
type NoteCollection []*Note

// NoteCollectionOf converts rows of the table of Note. A nil input is a nil
// collection.
func NoteCollectionOf(rows model.Rows) NoteCollection {
	if rows == nil {
		return nil
	}
	out := make(NoteCollection, len(rows))
	for i, e := range rows {
		out[i] = e.(*Note)
	}
	return out
}

func noteOf(e model.Entity) *Note {
	row, _ := e.(*Note)
	return row
}

// noteColumn turns a closure over NoteQuery into one over the core builder, so
// passing func(*NoteQuery) where a column goes adds a parenthesised group.
func noteColumn(column any) any {
	if group, ok := column.(func(*NoteQuery)); ok {
		return func(b *model.Builder) { group(&NoteQuery{b: b}) }
	}
	return column
}

// Clone returns an independent copy of the query.
func (q *NoteQuery) Clone() *NoteQuery { return &NoteQuery{b: q.b.Clone()} }

// Where adds a where clause; a func(*NoteQuery) in place of the column adds a group.
func (q *NoteQuery) Where(column any, args ...any) *NoteQuery {
	q.b.Where(noteColumn(column), args...)
	return q
}

// OrWhere adds an or-where clause; a func(*NoteQuery) in place of the column adds a group.
func (q *NoteQuery) OrWhere(column any, args ...any) *NoteQuery {
	q.b.OrWhere(noteColumn(column), args...)
	return q
}

// WhereNot adds a negated where clause, or a negated group.
func (q *NoteQuery) WhereNot(column any, args ...any) *NoteQuery {
	q.b.WhereNot(noteColumn(column), args...)
	return q
}

// OrWhereNot adds an or-joined negated where clause, or a negated group.
func (q *NoteQuery) OrWhereNot(column any, args ...any) *NoteQuery {
	q.b.OrWhereNot(noteColumn(column), args...)
	return q
}

func (q *NoteQuery) WhereIn(column any, values []any) *NoteQuery {
	q.b.WhereIn(column, values)
	return q
}

func (q *NoteQuery) WhereNotIn(column any, values []any) *NoteQuery {
	q.b.WhereNotIn(column, values)
	return q
}

func (q *NoteQuery) WhereNull(columns ...any) *NoteQuery {
	q.b.WhereNull(columns...)
	return q
}

func (q *NoteQuery) WhereNotNull(columns ...any) *NoteQuery {
	q.b.WhereNotNull(columns...)
	return q
}

func (q *NoteQuery) WhereBetween(column any, from, to any) *NoteQuery {
	q.b.WhereBetween(column, from, to)
	return q
}

func (q *NoteQuery) WhereColumn(first any, args ...any) *NoteQuery {
	q.b.WhereColumn(first, args...)
	return q
}

func (q *NoteQuery) WhereKey(id any) *NoteQuery {
	q.b.WhereKey(id)
	return q
}

func (q *NoteQuery) WhereExists(callback func(*query.Builder)) *NoteQuery {
	q.b.WhereExists(callback)
	return q
}

func (q *NoteQuery) WhereNotExists(callback func(*query.Builder)) *NoteQuery {
	q.b.WhereNotExists(callback)
	return q
}

func (q *NoteQuery) WhereHas(relation string, callback func(*query.Builder)) *NoteQuery {
	q.b.WhereHas(relation, callback)
	return q
}

func (q *NoteQuery) OrWhereHas(relation string, callback func(*query.Builder)) *NoteQuery {
	q.b.OrWhereHas(relation, callback)
	return q
}

func (q *NoteQuery) WhereDoesntHave(relation string, callback func(*query.Builder)) *NoteQuery {
	q.b.WhereDoesntHave(relation, callback)
	return q
}

func (q *NoteQuery) OrWhereDoesntHave(relation string, callback func(*query.Builder)) *NoteQuery {
	q.b.OrWhereDoesntHave(relation, callback)
	return q
}

func (q *NoteQuery) WhereRelation(relation string, column any, args ...any) *NoteQuery {
	q.b.WhereRelation(relation, column, args...)
	return q
}

func (q *NoteQuery) OrWhereRelation(relation string, column any, args ...any) *NoteQuery {
	q.b.OrWhereRelation(relation, column, args...)
	return q
}

func (q *NoteQuery) WhereHasCount(relation string, callback func(*query.Builder), operator string, count int) *NoteQuery {
	q.b.WhereHasCount(relation, callback, operator, count)
	return q
}

func (q *NoteQuery) WhereBelongsTo(relationshipName string, related ...model.Entity) *NoteQuery {
	q.b.WhereBelongsTo(relationshipName, related...)
	return q
}

func (q *NoteQuery) Has(relation, operator string, count int, boolean string, callback func(*query.Builder)) *NoteQuery {
	q.b.Has(relation, operator, count, boolean, callback)
	return q
}

func (q *NoteQuery) OrHas(relation, operator string, count int) *NoteQuery {
	q.b.OrHas(relation, operator, count)
	return q
}

func (q *NoteQuery) DoesntHave(relation, boolean string, callback func(*query.Builder)) *NoteQuery {
	q.b.DoesntHave(relation, boolean, callback)
	return q
}

func (q *NoteQuery) OrDoesntHave(relation string) *NoteQuery {
	q.b.OrDoesntHave(relation)
	return q
}

func (q *NoteQuery) Select(columns ...any) *NoteQuery {
	q.b.Select(columns...)
	return q
}

func (q *NoteQuery) AddSelect(columns ...any) *NoteQuery {
	q.b.AddSelect(columns...)
	return q
}

func (q *NoteQuery) SelectRaw(expression string, bindings ...any) *NoteQuery {
	q.b.SelectRaw(expression, bindings...)
	return q
}

func (q *NoteQuery) Join(table any, first any, args ...any) *NoteQuery {
	q.b.Join(table, first, args...)
	return q
}

func (q *NoteQuery) GroupBy(groups ...any) *NoteQuery {
	q.b.GroupBy(groups...)
	return q
}

func (q *NoteQuery) OrderBy(column any, direction ...string) *NoteQuery {
	q.b.OrderBy(column, direction...)
	return q
}

func (q *NoteQuery) OrderByDesc(column any) *NoteQuery {
	q.b.OrderByDesc(column)
	return q
}

func (q *NoteQuery) Latest(column ...string) *NoteQuery {
	q.b.Latest(column...)
	return q
}

func (q *NoteQuery) Oldest(column ...string) *NoteQuery {
	q.b.Oldest(column...)
	return q
}

func (q *NoteQuery) Limit(value int) *NoteQuery {
	q.b.Limit(value)
	return q
}

func (q *NoteQuery) Offset(value int) *NoteQuery {
	q.b.Offset(value)
	return q
}

func (q *NoteQuery) ForPage(page, perPage int) *NoteQuery {
	q.b.ForPage(page, perPage)
	return q
}

func (q *NoteQuery) With(relations ...string) *NoteQuery {
	q.b.With(relations...)
	return q
}

func (q *NoteQuery) WithCount(relations ...string) *NoteQuery {
	q.b.WithCount(relations...)
	return q
}

func (q *NoteQuery) WithExists(relation string) *NoteQuery {
	q.b.WithExists(relation)
	return q
}

func (q *NoteQuery) WithSum(relation, column string) *NoteQuery {
	q.b.WithSum(relation, column)
	return q
}

func (q *NoteQuery) WithAvg(relation, column string) *NoteQuery {
	q.b.WithAvg(relation, column)
	return q
}

func (q *NoteQuery) WithMin(relation, column string) *NoteQuery {
	q.b.WithMin(relation, column)
	return q
}

func (q *NoteQuery) WithMax(relation, column string) *NoteQuery {
	q.b.WithMax(relation, column)
	return q
}

func (q *NoteQuery) Without(relations ...string) *NoteQuery {
	q.b.Without(relations...)
	return q
}

func (q *NoteQuery) WithoutGlobalScope(identifier string) *NoteQuery {
	q.b.WithoutGlobalScope(identifier)
	return q
}

func (q *NoteQuery) WithoutGlobalScopes(identifiers ...string) *NoteQuery {
	q.b.WithoutGlobalScopes(identifiers...)
	return q
}

// Get runs the query and returns the rows.
func (q *NoteQuery) Get(ctx context.Context, g auth.Grant, columns ...any) (NoteCollection, error) {
	rows, err := q.b.Get(ctx, g, columns...)
	return NoteCollectionOf(rows), err
}

// First returns the first row, or nil and no error when there is none.
func (q *NoteQuery) First(ctx context.Context, g auth.Grant, columns ...any) (*Note, error) {
	e, err := q.b.First(ctx, g, columns...)
	return noteOf(e), err
}

func (q *NoteQuery) FirstOrFail(ctx context.Context, g auth.Grant, columns ...any) (*Note, error) {
	e, err := q.b.FirstOrFail(ctx, g, columns...)
	return noteOf(e), err
}

func (q *NoteQuery) FirstWhere(ctx context.Context, g auth.Grant, column any, args ...any) (*Note, error) {
	e, err := q.b.FirstWhere(ctx, g, column, args...)
	return noteOf(e), err
}

func (q *NoteQuery) FirstOrNew(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Note, error) {
	e, err := q.b.FirstOrNew(ctx, g, attributes, values)
	return noteOf(e), err
}

func (q *NoteQuery) FirstOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Note, error) {
	e, err := q.b.FirstOrCreate(ctx, g, attributes, values)
	return noteOf(e), err
}

func (q *NoteQuery) Find(ctx context.Context, g auth.Grant, id any, columns ...any) (*Note, error) {
	e, err := q.b.Find(ctx, g, id, columns...)
	return noteOf(e), err
}

func (q *NoteQuery) FindOrFail(ctx context.Context, g auth.Grant, id any, columns ...any) (*Note, error) {
	e, err := q.b.FindOrFail(ctx, g, id, columns...)
	return noteOf(e), err
}

func (q *NoteQuery) FindOrNew(ctx context.Context, g auth.Grant, id any, columns ...any) (*Note, error) {
	e, err := q.b.FindOrNew(ctx, g, id, columns...)
	return noteOf(e), err
}

func (q *NoteQuery) FindMany(ctx context.Context, g auth.Grant, ids []any, columns ...any) (NoteCollection, error) {
	rows, err := q.b.FindMany(ctx, g, ids, columns...)
	return NoteCollectionOf(rows), err
}

func (q *NoteQuery) Sole(ctx context.Context, g auth.Grant, columns ...any) (*Note, error) {
	e, err := q.b.Sole(ctx, g, columns...)
	return noteOf(e), err
}

func (q *NoteQuery) Create(ctx context.Context, g auth.Grant, attributes map[string]any) (*Note, error) {
	e, err := q.b.Create(ctx, g, attributes)
	return noteOf(e), err
}

func (q *NoteQuery) ForceCreate(ctx context.Context, g auth.Grant, attributes map[string]any) (*Note, error) {
	e, err := q.b.ForceCreate(ctx, g, attributes)
	return noteOf(e), err
}

func (q *NoteQuery) UpdateOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Note, error) {
	e, err := q.b.UpdateOrCreate(ctx, g, attributes, values)
	return noteOf(e), err
}

func (q *NoteQuery) Paginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (NoteCollection, *pagination.LengthAwarePage, error) {
	rows, meta, err := q.b.Paginate(ctx, g, perPage, page, opts, columns...)
	return NoteCollectionOf(rows), meta, err
}

func (q *NoteQuery) SimplePaginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (NoteCollection, *pagination.Page, error) {
	rows, meta, err := q.b.SimplePaginate(ctx, g, perPage, page, opts, columns...)
	return NoteCollectionOf(rows), meta, err
}

func (q *NoteQuery) CursorPaginate(ctx context.Context, g auth.Grant, perPage int, cursor *pagination.Cursor, opts pagination.Options, columns ...any) (NoteCollection, *pagination.CursorPage, error) {
	rows, meta, err := q.b.CursorPaginate(ctx, g, perPage, cursor, opts, columns...)
	return NoteCollectionOf(rows), meta, err
}

func (q *NoteQuery) Chunk(ctx context.Context, g auth.Grant, count int, callback func(NoteCollection, int) (bool, error)) error {
	return q.b.Chunk(ctx, g, count, func(rows model.Rows, page int) (bool, error) {
		return callback(NoteCollectionOf(rows), page)
	})
}

func (q *NoteQuery) Each(ctx context.Context, g auth.Grant, count int, callback func(*Note, int) (bool, error)) error {
	return q.b.Each(ctx, g, count, func(e model.Entity, index int) (bool, error) {
		return callback(noteOf(e), index)
	})
}

func (q *NoteQuery) Cursor(ctx context.Context, g auth.Grant) iter.Seq2[*Note, error] {
	return func(yield func(*Note, error) bool) {
		for e, err := range q.b.Cursor(ctx, g) {
			if !yield(noteOf(e), err) {
				return
			}
		}
	}
}

func (q *NoteQuery) Count(ctx context.Context, g auth.Grant, columns ...any) (int64, error) {
	return q.b.Count(ctx, g, columns...)
}

func (q *NoteQuery) Exists(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.Exists(ctx, g)
}

func (q *NoteQuery) DoesntExist(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.DoesntExist(ctx, g)
}

func (q *NoteQuery) Pluck(ctx context.Context, g auth.Grant, column string) ([]any, error) {
	return q.b.Pluck(ctx, g, column)
}

func (q *NoteQuery) Value(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.Value(ctx, g, column)
}

func (q *NoteQuery) ValueOrFail(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.ValueOrFail(ctx, g, column)
}

func (q *NoteQuery) SoleValue(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.SoleValue(ctx, g, column)
}

func (q *NoteQuery) Sum(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Sum(ctx, g, column)
}

func (q *NoteQuery) Avg(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Avg(ctx, g, column)
}

func (q *NoteQuery) Min(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Min(ctx, g, column)
}

func (q *NoteQuery) Max(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Max(ctx, g, column)
}

func (q *NoteQuery) Update(ctx context.Context, g auth.Grant, values map[string]any) (int64, error) {
	return q.b.Update(ctx, g, values)
}

func (q *NoteQuery) Delete(ctx context.Context, g auth.Grant) (int64, error) {
	return q.b.Delete(ctx, g)
}

func (q *NoteQuery) Increment(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Increment(ctx, g, column, amount, extra)
}

func (q *NoteQuery) Decrement(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Decrement(ctx, g, column, amount, extra)
}

func (q *NoteQuery) Insert(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.Insert(ctx, g, values...)
}

func (q *NoteQuery) InsertOrIgnore(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.InsertOrIgnore(ctx, g, values...)
}

func (q *NoteQuery) Upsert(ctx context.Context, g auth.Grant, values []map[string]any, uniqueBy, update []string) (int64, error) {
	return q.b.Upsert(ctx, g, values, uniqueBy, update)
}

func (q *NoteQuery) Touch(ctx context.Context, g auth.Grant, column ...string) (int64, error) {
	return q.b.Touch(ctx, g, column...)
}

// Rows converts the collection back to the core's rows.
func (c NoteCollection) Rows() model.Rows {
	out := make(model.Rows, len(c))
	for i, row := range c {
		out[i] = row
	}
	return out
}

func (c NoteCollection) ModelKeys() []any { return c.Rows().ModelKeys() }

func (c NoteCollection) Find(key any) *Note { return noteOf(c.Rows().Find(key)) }

func (c NoteCollection) FindOrFail(key any) (*Note, error) {
	e, err := c.Rows().FindOrFail(key)
	return noteOf(e), err
}

func (c NoteCollection) Contains(key any) bool { return c.Rows().Contains(key) }

func (c NoteCollection) Pluck(column string) []any { return c.Rows().Pluck(column) }

func (c NoteCollection) Only(keys ...any) NoteCollection {
	return NoteCollectionOf(c.Rows().Only(keys...))
}

func (c NoteCollection) Except(keys ...any) NoteCollection {
	return NoteCollectionOf(c.Rows().Except(keys...))
}

func (c NoteCollection) Unique() NoteCollection { return NoteCollectionOf(c.Rows().Unique()) }

func (c NoteCollection) Load(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().Load(ctx, g, relations...)
}

func (c NoteCollection) LoadMissing(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadMissing(ctx, g, relations...)
}

func (c NoteCollection) LoadCount(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadCount(ctx, g, relations...)
}

func (c NoteCollection) Fresh(ctx context.Context, g auth.Grant, with ...string) (NoteCollection, error) {
	rows, err := c.Rows().Fresh(ctx, g, with...)
	return NoteCollectionOf(rows), err
}

func (c NoteCollection) ToArray() []map[string]any { return c.Rows().ToArray() }

// Fresh reads the row again, as a new Note; it shadows the untyped one the
// embedded model promotes.
func (row *Note) Fresh(ctx context.Context, g auth.Grant, with ...string) (*Note, error) {
	e, err := row.Model.Fresh(ctx, g, with...)
	return noteOf(e), err
}

// Replicate returns an unsaved copy of the row without its key; it shadows the
// untyped one the embedded model promotes.
func (row *Note) Replicate(except ...string) (*Note, error) {
	e, err := row.Model.Replicate(except...)
	return noteOf(e), err
}
