// Code generated by aru model:build from PersonalAccessToken.go. DO NOT EDIT.

package models

import (
	"context"
	"iter"

	"github.com/arandu-io/hesape/auth"
	"github.com/arandu-io/hesape/database/model"
	"github.com/arandu-io/hesape/database/query"
	"github.com/arandu-io/hesape/pagination"
)

// PersonalAccessTokens starts a query on the table of PersonalAccessToken, through db.
//
// Global scopes are on and, unless the table is Global, every statement is
// filtered by the tenant of the Grant its terminal takes.
func PersonalAccessTokens(db model.DB) *PersonalAccessTokenQuery {
	return &PersonalAccessTokenQuery{b: personalAccessTokenTable.Query(db)}
}

// PersonalAccessTokenQuery is a query on the table of PersonalAccessToken.
//
// The methods that build return the query, so they chain. The methods that run
// take a context and an auth.Grant, and return PersonalAccessToken rows or a value; there is
// no way to run one without a Grant.
type PersonalAccessTokenQuery struct{ b *model.Builder }

// Base returns the core builder the query forwards to. It is for code in this
// package -- a local scope in the custom block of PersonalAccessToken.go -- and for the
// factory, which builds rows through it.
func (q *PersonalAccessTokenQuery) Base() *model.Builder { return q.b }

// New returns an empty PersonalAccessToken on the query's connection, not yet saved, filled
// with what WithAttributes recorded on the query.
func (q *PersonalAccessTokenQuery) New() (*PersonalAccessToken, error) {
	e, err := q.b.NewModelInstance(nil)
	return personalAccessTokenOf(e), err
}

// PersonalAccessTokenCollection is rows of PersonalAccessToken, as a query returns them.
type PersonalAccessTokenCollection []*PersonalAccessToken

// PersonalAccessTokenCollectionOf converts rows of the table of PersonalAccessToken. A nil input is a nil
// collection.
func PersonalAccessTokenCollectionOf(rows model.Rows) PersonalAccessTokenCollection {
	if rows == nil {
		return nil
	}
	out := make(PersonalAccessTokenCollection, len(rows))
	for i, e := range rows {
		out[i] = e.(*PersonalAccessToken)
	}
	return out
}

func personalAccessTokenOf(e model.Entity) *PersonalAccessToken {
	row, _ := e.(*PersonalAccessToken)
	return row
}

// personalAccessTokenColumn turns a closure over PersonalAccessTokenQuery into one over the core builder, so
// passing func(*PersonalAccessTokenQuery) where a column goes adds a parenthesised group.
func personalAccessTokenColumn(column any) any {
	if group, ok := column.(func(*PersonalAccessTokenQuery)); ok {
		return func(b *model.Builder) { group(&PersonalAccessTokenQuery{b: b}) }
	}
	return column
}

// Clone returns an independent copy of the query.
func (q *PersonalAccessTokenQuery) Clone() *PersonalAccessTokenQuery {
	return &PersonalAccessTokenQuery{b: q.b.Clone()}
}

// Where adds a where clause; a func(*PersonalAccessTokenQuery) in place of the column adds a group.
func (q *PersonalAccessTokenQuery) Where(column any, args ...any) *PersonalAccessTokenQuery {
	q.b.Where(personalAccessTokenColumn(column), args...)
	return q
}

// OrWhere adds an or-where clause; a func(*PersonalAccessTokenQuery) in place of the column adds a group.
func (q *PersonalAccessTokenQuery) OrWhere(column any, args ...any) *PersonalAccessTokenQuery {
	q.b.OrWhere(personalAccessTokenColumn(column), args...)
	return q
}

// WhereNot adds a negated where clause, or a negated group.
func (q *PersonalAccessTokenQuery) WhereNot(column any, args ...any) *PersonalAccessTokenQuery {
	q.b.WhereNot(personalAccessTokenColumn(column), args...)
	return q
}

// OrWhereNot adds an or-joined negated where clause, or a negated group.
func (q *PersonalAccessTokenQuery) OrWhereNot(column any, args ...any) *PersonalAccessTokenQuery {
	q.b.OrWhereNot(personalAccessTokenColumn(column), args...)
	return q
}

func (q *PersonalAccessTokenQuery) WhereIn(column any, values []any) *PersonalAccessTokenQuery {
	q.b.WhereIn(column, values)
	return q
}

func (q *PersonalAccessTokenQuery) WhereNotIn(column any, values []any) *PersonalAccessTokenQuery {
	q.b.WhereNotIn(column, values)
	return q
}

func (q *PersonalAccessTokenQuery) WhereNull(columns ...any) *PersonalAccessTokenQuery {
	q.b.WhereNull(columns...)
	return q
}

func (q *PersonalAccessTokenQuery) WhereNotNull(columns ...any) *PersonalAccessTokenQuery {
	q.b.WhereNotNull(columns...)
	return q
}

func (q *PersonalAccessTokenQuery) WhereBetween(column any, from, to any) *PersonalAccessTokenQuery {
	q.b.WhereBetween(column, from, to)
	return q
}

func (q *PersonalAccessTokenQuery) WhereColumn(first any, args ...any) *PersonalAccessTokenQuery {
	q.b.WhereColumn(first, args...)
	return q
}

func (q *PersonalAccessTokenQuery) WhereKey(id any) *PersonalAccessTokenQuery {
	q.b.WhereKey(id)
	return q
}

func (q *PersonalAccessTokenQuery) WhereExists(callback func(*query.Builder)) *PersonalAccessTokenQuery {
	q.b.WhereExists(callback)
	return q
}

func (q *PersonalAccessTokenQuery) WhereNotExists(callback func(*query.Builder)) *PersonalAccessTokenQuery {
	q.b.WhereNotExists(callback)
	return q
}

func (q *PersonalAccessTokenQuery) WhereHas(relation string, callback func(*query.Builder)) *PersonalAccessTokenQuery {
	q.b.WhereHas(relation, callback)
	return q
}

func (q *PersonalAccessTokenQuery) OrWhereHas(relation string, callback func(*query.Builder)) *PersonalAccessTokenQuery {
	q.b.OrWhereHas(relation, callback)
	return q
}

func (q *PersonalAccessTokenQuery) WhereDoesntHave(relation string, callback func(*query.Builder)) *PersonalAccessTokenQuery {
	q.b.WhereDoesntHave(relation, callback)
	return q
}

func (q *PersonalAccessTokenQuery) OrWhereDoesntHave(relation string, callback func(*query.Builder)) *PersonalAccessTokenQuery {
	q.b.OrWhereDoesntHave(relation, callback)
	return q
}

func (q *PersonalAccessTokenQuery) WhereRelation(relation string, column any, args ...any) *PersonalAccessTokenQuery {
	q.b.WhereRelation(relation, column, args...)
	return q
}

func (q *PersonalAccessTokenQuery) OrWhereRelation(relation string, column any, args ...any) *PersonalAccessTokenQuery {
	q.b.OrWhereRelation(relation, column, args...)
	return q
}

func (q *PersonalAccessTokenQuery) WhereHasCount(relation string, callback func(*query.Builder), operator string, count int) *PersonalAccessTokenQuery {
	q.b.WhereHasCount(relation, callback, operator, count)
	return q
}

func (q *PersonalAccessTokenQuery) WhereBelongsTo(relationshipName string, related ...model.Entity) *PersonalAccessTokenQuery {
	q.b.WhereBelongsTo(relationshipName, related...)
	return q
}

func (q *PersonalAccessTokenQuery) Has(relation, operator string, count int, boolean string, callback func(*query.Builder)) *PersonalAccessTokenQuery {
	q.b.Has(relation, operator, count, boolean, callback)
	return q
}

func (q *PersonalAccessTokenQuery) OrHas(relation, operator string, count int) *PersonalAccessTokenQuery {
	q.b.OrHas(relation, operator, count)
	return q
}

func (q *PersonalAccessTokenQuery) DoesntHave(relation, boolean string, callback func(*query.Builder)) *PersonalAccessTokenQuery {
	q.b.DoesntHave(relation, boolean, callback)
	return q
}

func (q *PersonalAccessTokenQuery) OrDoesntHave(relation string) *PersonalAccessTokenQuery {
	q.b.OrDoesntHave(relation)
	return q
}

func (q *PersonalAccessTokenQuery) Select(columns ...any) *PersonalAccessTokenQuery {
	q.b.Select(columns...)
	return q
}

func (q *PersonalAccessTokenQuery) AddSelect(columns ...any) *PersonalAccessTokenQuery {
	q.b.AddSelect(columns...)
	return q
}

func (q *PersonalAccessTokenQuery) SelectRaw(expression string, bindings ...any) *PersonalAccessTokenQuery {
	q.b.SelectRaw(expression, bindings...)
	return q
}

func (q *PersonalAccessTokenQuery) Join(table any, first any, args ...any) *PersonalAccessTokenQuery {
	q.b.Join(table, first, args...)
	return q
}

func (q *PersonalAccessTokenQuery) GroupBy(groups ...any) *PersonalAccessTokenQuery {
	q.b.GroupBy(groups...)
	return q
}

func (q *PersonalAccessTokenQuery) OrderBy(column any, direction ...string) *PersonalAccessTokenQuery {
	q.b.OrderBy(column, direction...)
	return q
}

func (q *PersonalAccessTokenQuery) OrderByDesc(column any) *PersonalAccessTokenQuery {
	q.b.OrderByDesc(column)
	return q
}

func (q *PersonalAccessTokenQuery) Latest(column ...string) *PersonalAccessTokenQuery {
	q.b.Latest(column...)
	return q
}

func (q *PersonalAccessTokenQuery) Oldest(column ...string) *PersonalAccessTokenQuery {
	q.b.Oldest(column...)
	return q
}

func (q *PersonalAccessTokenQuery) Limit(value int) *PersonalAccessTokenQuery {
	q.b.Limit(value)
	return q
}

func (q *PersonalAccessTokenQuery) Offset(value int) *PersonalAccessTokenQuery {
	q.b.Offset(value)
	return q
}

func (q *PersonalAccessTokenQuery) ForPage(page, perPage int) *PersonalAccessTokenQuery {
	q.b.ForPage(page, perPage)
	return q
}

func (q *PersonalAccessTokenQuery) With(relations ...string) *PersonalAccessTokenQuery {
	q.b.With(relations...)
	return q
}

func (q *PersonalAccessTokenQuery) WithCount(relations ...string) *PersonalAccessTokenQuery {
	q.b.WithCount(relations...)
	return q
}

func (q *PersonalAccessTokenQuery) WithExists(relation string) *PersonalAccessTokenQuery {
	q.b.WithExists(relation)
	return q
}

func (q *PersonalAccessTokenQuery) WithSum(relation, column string) *PersonalAccessTokenQuery {
	q.b.WithSum(relation, column)
	return q
}

func (q *PersonalAccessTokenQuery) WithAvg(relation, column string) *PersonalAccessTokenQuery {
	q.b.WithAvg(relation, column)
	return q
}

func (q *PersonalAccessTokenQuery) WithMin(relation, column string) *PersonalAccessTokenQuery {
	q.b.WithMin(relation, column)
	return q
}

func (q *PersonalAccessTokenQuery) WithMax(relation, column string) *PersonalAccessTokenQuery {
	q.b.WithMax(relation, column)
	return q
}

func (q *PersonalAccessTokenQuery) Without(relations ...string) *PersonalAccessTokenQuery {
	q.b.Without(relations...)
	return q
}

func (q *PersonalAccessTokenQuery) WithoutGlobalScope(identifier string) *PersonalAccessTokenQuery {
	q.b.WithoutGlobalScope(identifier)
	return q
}

func (q *PersonalAccessTokenQuery) WithoutGlobalScopes(identifiers ...string) *PersonalAccessTokenQuery {
	q.b.WithoutGlobalScopes(identifiers...)
	return q
}

// Get runs the query and returns the rows.
func (q *PersonalAccessTokenQuery) Get(ctx context.Context, g auth.Grant, columns ...any) (PersonalAccessTokenCollection, error) {
	rows, err := q.b.Get(ctx, g, columns...)
	return PersonalAccessTokenCollectionOf(rows), err
}

// First returns the first row, or nil and no error when there is none.
func (q *PersonalAccessTokenQuery) First(ctx context.Context, g auth.Grant, columns ...any) (*PersonalAccessToken, error) {
	e, err := q.b.First(ctx, g, columns...)
	return personalAccessTokenOf(e), err
}

func (q *PersonalAccessTokenQuery) FirstOrFail(ctx context.Context, g auth.Grant, columns ...any) (*PersonalAccessToken, error) {
	e, err := q.b.FirstOrFail(ctx, g, columns...)
	return personalAccessTokenOf(e), err
}

func (q *PersonalAccessTokenQuery) FirstWhere(ctx context.Context, g auth.Grant, column any, args ...any) (*PersonalAccessToken, error) {
	e, err := q.b.FirstWhere(ctx, g, column, args...)
	return personalAccessTokenOf(e), err
}

func (q *PersonalAccessTokenQuery) FirstOrNew(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*PersonalAccessToken, error) {
	e, err := q.b.FirstOrNew(ctx, g, attributes, values)
	return personalAccessTokenOf(e), err
}

func (q *PersonalAccessTokenQuery) FirstOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*PersonalAccessToken, error) {
	e, err := q.b.FirstOrCreate(ctx, g, attributes, values)
	return personalAccessTokenOf(e), err
}

func (q *PersonalAccessTokenQuery) Find(ctx context.Context, g auth.Grant, id any, columns ...any) (*PersonalAccessToken, error) {
	e, err := q.b.Find(ctx, g, id, columns...)
	return personalAccessTokenOf(e), err
}

func (q *PersonalAccessTokenQuery) FindOrFail(ctx context.Context, g auth.Grant, id any, columns ...any) (*PersonalAccessToken, error) {
	e, err := q.b.FindOrFail(ctx, g, id, columns...)
	return personalAccessTokenOf(e), err
}

func (q *PersonalAccessTokenQuery) FindOrNew(ctx context.Context, g auth.Grant, id any, columns ...any) (*PersonalAccessToken, error) {
	e, err := q.b.FindOrNew(ctx, g, id, columns...)
	return personalAccessTokenOf(e), err
}

func (q *PersonalAccessTokenQuery) FindMany(ctx context.Context, g auth.Grant, ids []any, columns ...any) (PersonalAccessTokenCollection, error) {
	rows, err := q.b.FindMany(ctx, g, ids, columns...)
	return PersonalAccessTokenCollectionOf(rows), err
}

func (q *PersonalAccessTokenQuery) Sole(ctx context.Context, g auth.Grant, columns ...any) (*PersonalAccessToken, error) {
	e, err := q.b.Sole(ctx, g, columns...)
	return personalAccessTokenOf(e), err
}

func (q *PersonalAccessTokenQuery) Create(ctx context.Context, g auth.Grant, attributes map[string]any) (*PersonalAccessToken, error) {
	e, err := q.b.Create(ctx, g, attributes)
	return personalAccessTokenOf(e), err
}

func (q *PersonalAccessTokenQuery) ForceCreate(ctx context.Context, g auth.Grant, attributes map[string]any) (*PersonalAccessToken, error) {
	e, err := q.b.ForceCreate(ctx, g, attributes)
	return personalAccessTokenOf(e), err
}

func (q *PersonalAccessTokenQuery) UpdateOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*PersonalAccessToken, error) {
	e, err := q.b.UpdateOrCreate(ctx, g, attributes, values)
	return personalAccessTokenOf(e), err
}

func (q *PersonalAccessTokenQuery) Paginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (PersonalAccessTokenCollection, *pagination.LengthAwarePage, error) {
	rows, meta, err := q.b.Paginate(ctx, g, perPage, page, opts, columns...)
	return PersonalAccessTokenCollectionOf(rows), meta, err
}

func (q *PersonalAccessTokenQuery) SimplePaginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (PersonalAccessTokenCollection, *pagination.Page, error) {
	rows, meta, err := q.b.SimplePaginate(ctx, g, perPage, page, opts, columns...)
	return PersonalAccessTokenCollectionOf(rows), meta, err
}

func (q *PersonalAccessTokenQuery) CursorPaginate(ctx context.Context, g auth.Grant, perPage int, cursor *pagination.Cursor, opts pagination.Options, columns ...any) (PersonalAccessTokenCollection, *pagination.CursorPage, error) {
	rows, meta, err := q.b.CursorPaginate(ctx, g, perPage, cursor, opts, columns...)
	return PersonalAccessTokenCollectionOf(rows), meta, err
}

func (q *PersonalAccessTokenQuery) Chunk(ctx context.Context, g auth.Grant, count int, callback func(PersonalAccessTokenCollection, int) (bool, error)) error {
	return q.b.Chunk(ctx, g, count, func(rows model.Rows, page int) (bool, error) {
		return callback(PersonalAccessTokenCollectionOf(rows), page)
	})
}

func (q *PersonalAccessTokenQuery) Each(ctx context.Context, g auth.Grant, count int, callback func(*PersonalAccessToken, int) (bool, error)) error {
	return q.b.Each(ctx, g, count, func(e model.Entity, index int) (bool, error) {
		return callback(personalAccessTokenOf(e), index)
	})
}

func (q *PersonalAccessTokenQuery) Cursor(ctx context.Context, g auth.Grant) iter.Seq2[*PersonalAccessToken, error] {
	return func(yield func(*PersonalAccessToken, error) bool) {
		for e, err := range q.b.Cursor(ctx, g) {
			if !yield(personalAccessTokenOf(e), err) {
				return
			}
		}
	}
}

func (q *PersonalAccessTokenQuery) Count(ctx context.Context, g auth.Grant, columns ...any) (int64, error) {
	return q.b.Count(ctx, g, columns...)
}

func (q *PersonalAccessTokenQuery) Exists(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.Exists(ctx, g)
}

func (q *PersonalAccessTokenQuery) DoesntExist(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.DoesntExist(ctx, g)
}

func (q *PersonalAccessTokenQuery) Pluck(ctx context.Context, g auth.Grant, column string) ([]any, error) {
	return q.b.Pluck(ctx, g, column)
}

func (q *PersonalAccessTokenQuery) Value(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.Value(ctx, g, column)
}

func (q *PersonalAccessTokenQuery) ValueOrFail(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.ValueOrFail(ctx, g, column)
}

func (q *PersonalAccessTokenQuery) SoleValue(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.SoleValue(ctx, g, column)
}

func (q *PersonalAccessTokenQuery) Sum(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Sum(ctx, g, column)
}

func (q *PersonalAccessTokenQuery) Avg(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Avg(ctx, g, column)
}

func (q *PersonalAccessTokenQuery) Min(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Min(ctx, g, column)
}

func (q *PersonalAccessTokenQuery) Max(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Max(ctx, g, column)
}

func (q *PersonalAccessTokenQuery) Update(ctx context.Context, g auth.Grant, values map[string]any) (int64, error) {
	return q.b.Update(ctx, g, values)
}

func (q *PersonalAccessTokenQuery) Delete(ctx context.Context, g auth.Grant) (int64, error) {
	return q.b.Delete(ctx, g)
}

func (q *PersonalAccessTokenQuery) Increment(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Increment(ctx, g, column, amount, extra)
}

func (q *PersonalAccessTokenQuery) Decrement(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Decrement(ctx, g, column, amount, extra)
}

func (q *PersonalAccessTokenQuery) Insert(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.Insert(ctx, g, values...)
}

func (q *PersonalAccessTokenQuery) InsertOrIgnore(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.InsertOrIgnore(ctx, g, values...)
}

func (q *PersonalAccessTokenQuery) Upsert(ctx context.Context, g auth.Grant, values []map[string]any, uniqueBy, update []string) (int64, error) {
	return q.b.Upsert(ctx, g, values, uniqueBy, update)
}

func (q *PersonalAccessTokenQuery) Touch(ctx context.Context, g auth.Grant, column ...string) (int64, error) {
	return q.b.Touch(ctx, g, column...)
}

// Rows converts the collection back to the core's rows.
func (c PersonalAccessTokenCollection) Rows() model.Rows {
	out := make(model.Rows, len(c))
	for i, row := range c {
		out[i] = row
	}
	return out
}

func (c PersonalAccessTokenCollection) ModelKeys() []any { return c.Rows().ModelKeys() }

func (c PersonalAccessTokenCollection) Find(key any) *PersonalAccessToken {
	return personalAccessTokenOf(c.Rows().Find(key))
}

func (c PersonalAccessTokenCollection) FindOrFail(key any) (*PersonalAccessToken, error) {
	e, err := c.Rows().FindOrFail(key)
	return personalAccessTokenOf(e), err
}

func (c PersonalAccessTokenCollection) Contains(key any) bool { return c.Rows().Contains(key) }

func (c PersonalAccessTokenCollection) Pluck(column string) []any { return c.Rows().Pluck(column) }

func (c PersonalAccessTokenCollection) Only(keys ...any) PersonalAccessTokenCollection {
	return PersonalAccessTokenCollectionOf(c.Rows().Only(keys...))
}

func (c PersonalAccessTokenCollection) Except(keys ...any) PersonalAccessTokenCollection {
	return PersonalAccessTokenCollectionOf(c.Rows().Except(keys...))
}

func (c PersonalAccessTokenCollection) Unique() PersonalAccessTokenCollection {
	return PersonalAccessTokenCollectionOf(c.Rows().Unique())
}

func (c PersonalAccessTokenCollection) Load(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().Load(ctx, g, relations...)
}

func (c PersonalAccessTokenCollection) LoadMissing(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadMissing(ctx, g, relations...)
}

func (c PersonalAccessTokenCollection) LoadCount(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadCount(ctx, g, relations...)
}

func (c PersonalAccessTokenCollection) Fresh(ctx context.Context, g auth.Grant, with ...string) (PersonalAccessTokenCollection, error) {
	rows, err := c.Rows().Fresh(ctx, g, with...)
	return PersonalAccessTokenCollectionOf(rows), err
}

func (c PersonalAccessTokenCollection) ToArray() []map[string]any { return c.Rows().ToArray() }

// Fresh reads the row again, as a new PersonalAccessToken; it shadows the untyped one the
// embedded model promotes.
func (row *PersonalAccessToken) Fresh(ctx context.Context, g auth.Grant, with ...string) (*PersonalAccessToken, error) {
	e, err := row.Model.Fresh(ctx, g, with...)
	return personalAccessTokenOf(e), err
}

// Replicate returns an unsaved copy of the row without its key; it shadows the
// untyped one the embedded model promotes.
func (row *PersonalAccessToken) Replicate(except ...string) (*PersonalAccessToken, error) {
	e, err := row.Model.Replicate(except...)
	return personalAccessTokenOf(e), err
}
