// Code generated by aru model:build from TwoFactor.go. DO NOT EDIT.

package models

import (
	"context"
	"iter"

	"github.com/arandu-io/hesape/auth"
	"github.com/arandu-io/hesape/database/model"
	"github.com/arandu-io/hesape/database/query"
	"github.com/arandu-io/hesape/pagination"
)

// RecoveryCodes starts a query on the table of RecoveryCode, through db.
//
// Global scopes are on and, unless the table is Global, every statement is
// filtered by the tenant of the Grant its terminal takes.
func RecoveryCodes(db model.DB) *RecoveryCodeQuery {
	return &RecoveryCodeQuery{b: recoveryCodeTable.Query(db)}
}

// RecoveryCodeQuery is a query on the table of RecoveryCode.
//
// The methods that build return the query, so they chain. The methods that run
// take a context and an auth.Grant, and return RecoveryCode rows or a value; there is
// no way to run one without a Grant.
type RecoveryCodeQuery struct{ b *model.Builder }

// Base returns the core builder the query forwards to. It is for code in this
// package -- a local scope in the custom block of TwoFactor.go -- and for the
// factory, which builds rows through it.
func (q *RecoveryCodeQuery) Base() *model.Builder { return q.b }

// New returns an empty RecoveryCode on the query's connection, not yet saved, filled
// with what WithAttributes recorded on the query.
func (q *RecoveryCodeQuery) New() (*RecoveryCode, error) {
	e, err := q.b.NewModelInstance(nil)
	return recoveryCodeOf(e), err
}

// RecoveryCodeCollection is rows of RecoveryCode, as a query returns them.
type RecoveryCodeCollection []*RecoveryCode

// RecoveryCodeCollectionOf converts rows of the table of RecoveryCode. A nil input is a nil
// collection.
func RecoveryCodeCollectionOf(rows model.Rows) RecoveryCodeCollection {
	if rows == nil {
		return nil
	}
	out := make(RecoveryCodeCollection, len(rows))
	for i, e := range rows {
		out[i] = e.(*RecoveryCode)
	}
	return out
}

func recoveryCodeOf(e model.Entity) *RecoveryCode {
	row, _ := e.(*RecoveryCode)
	return row
}

// recoveryCodeColumn turns a closure over RecoveryCodeQuery into one over the core builder, so
// passing func(*RecoveryCodeQuery) where a column goes adds a parenthesised group.
func recoveryCodeColumn(column any) any {
	if group, ok := column.(func(*RecoveryCodeQuery)); ok {
		return func(b *model.Builder) { group(&RecoveryCodeQuery{b: b}) }
	}
	return column
}

// Clone returns an independent copy of the query.
func (q *RecoveryCodeQuery) Clone() *RecoveryCodeQuery { return &RecoveryCodeQuery{b: q.b.Clone()} }

// Where adds a where clause; a func(*RecoveryCodeQuery) in place of the column adds a group.
func (q *RecoveryCodeQuery) Where(column any, args ...any) *RecoveryCodeQuery {
	q.b.Where(recoveryCodeColumn(column), args...)
	return q
}

// OrWhere adds an or-where clause; a func(*RecoveryCodeQuery) in place of the column adds a group.
func (q *RecoveryCodeQuery) OrWhere(column any, args ...any) *RecoveryCodeQuery {
	q.b.OrWhere(recoveryCodeColumn(column), args...)
	return q
}

// WhereNot adds a negated where clause, or a negated group.
func (q *RecoveryCodeQuery) WhereNot(column any, args ...any) *RecoveryCodeQuery {
	q.b.WhereNot(recoveryCodeColumn(column), args...)
	return q
}

// OrWhereNot adds an or-joined negated where clause, or a negated group.
func (q *RecoveryCodeQuery) OrWhereNot(column any, args ...any) *RecoveryCodeQuery {
	q.b.OrWhereNot(recoveryCodeColumn(column), args...)
	return q
}

func (q *RecoveryCodeQuery) WhereIn(column any, values []any) *RecoveryCodeQuery {
	q.b.WhereIn(column, values)
	return q
}

func (q *RecoveryCodeQuery) WhereNotIn(column any, values []any) *RecoveryCodeQuery {
	q.b.WhereNotIn(column, values)
	return q
}

func (q *RecoveryCodeQuery) WhereNull(columns ...any) *RecoveryCodeQuery {
	q.b.WhereNull(columns...)
	return q
}

func (q *RecoveryCodeQuery) WhereNotNull(columns ...any) *RecoveryCodeQuery {
	q.b.WhereNotNull(columns...)
	return q
}

func (q *RecoveryCodeQuery) WhereBetween(column any, from, to any) *RecoveryCodeQuery {
	q.b.WhereBetween(column, from, to)
	return q
}

func (q *RecoveryCodeQuery) WhereColumn(first any, args ...any) *RecoveryCodeQuery {
	q.b.WhereColumn(first, args...)
	return q
}

func (q *RecoveryCodeQuery) WhereKey(id any) *RecoveryCodeQuery {
	q.b.WhereKey(id)
	return q
}

func (q *RecoveryCodeQuery) WhereExists(callback func(*query.Builder)) *RecoveryCodeQuery {
	q.b.WhereExists(callback)
	return q
}

func (q *RecoveryCodeQuery) WhereNotExists(callback func(*query.Builder)) *RecoveryCodeQuery {
	q.b.WhereNotExists(callback)
	return q
}

func (q *RecoveryCodeQuery) WhereHas(relation string, callback func(*query.Builder)) *RecoveryCodeQuery {
	q.b.WhereHas(relation, callback)
	return q
}

func (q *RecoveryCodeQuery) OrWhereHas(relation string, callback func(*query.Builder)) *RecoveryCodeQuery {
	q.b.OrWhereHas(relation, callback)
	return q
}

func (q *RecoveryCodeQuery) WhereDoesntHave(relation string, callback func(*query.Builder)) *RecoveryCodeQuery {
	q.b.WhereDoesntHave(relation, callback)
	return q
}

func (q *RecoveryCodeQuery) OrWhereDoesntHave(relation string, callback func(*query.Builder)) *RecoveryCodeQuery {
	q.b.OrWhereDoesntHave(relation, callback)
	return q
}

func (q *RecoveryCodeQuery) WhereRelation(relation string, column any, args ...any) *RecoveryCodeQuery {
	q.b.WhereRelation(relation, column, args...)
	return q
}

func (q *RecoveryCodeQuery) OrWhereRelation(relation string, column any, args ...any) *RecoveryCodeQuery {
	q.b.OrWhereRelation(relation, column, args...)
	return q
}

func (q *RecoveryCodeQuery) WhereHasCount(relation string, callback func(*query.Builder), operator string, count int) *RecoveryCodeQuery {
	q.b.WhereHasCount(relation, callback, operator, count)
	return q
}

func (q *RecoveryCodeQuery) WhereBelongsTo(relationshipName string, related ...model.Entity) *RecoveryCodeQuery {
	q.b.WhereBelongsTo(relationshipName, related...)
	return q
}

func (q *RecoveryCodeQuery) Has(relation, operator string, count int, boolean string, callback func(*query.Builder)) *RecoveryCodeQuery {
	q.b.Has(relation, operator, count, boolean, callback)
	return q
}

func (q *RecoveryCodeQuery) OrHas(relation, operator string, count int) *RecoveryCodeQuery {
	q.b.OrHas(relation, operator, count)
	return q
}

func (q *RecoveryCodeQuery) DoesntHave(relation, boolean string, callback func(*query.Builder)) *RecoveryCodeQuery {
	q.b.DoesntHave(relation, boolean, callback)
	return q
}

func (q *RecoveryCodeQuery) OrDoesntHave(relation string) *RecoveryCodeQuery {
	q.b.OrDoesntHave(relation)
	return q
}

func (q *RecoveryCodeQuery) Select(columns ...any) *RecoveryCodeQuery {
	q.b.Select(columns...)
	return q
}

func (q *RecoveryCodeQuery) AddSelect(columns ...any) *RecoveryCodeQuery {
	q.b.AddSelect(columns...)
	return q
}

func (q *RecoveryCodeQuery) SelectRaw(expression string, bindings ...any) *RecoveryCodeQuery {
	q.b.SelectRaw(expression, bindings...)
	return q
}

func (q *RecoveryCodeQuery) Join(table any, first any, args ...any) *RecoveryCodeQuery {
	q.b.Join(table, first, args...)
	return q
}

func (q *RecoveryCodeQuery) GroupBy(groups ...any) *RecoveryCodeQuery {
	q.b.GroupBy(groups...)
	return q
}

func (q *RecoveryCodeQuery) OrderBy(column any, direction ...string) *RecoveryCodeQuery {
	q.b.OrderBy(column, direction...)
	return q
}

func (q *RecoveryCodeQuery) OrderByDesc(column any) *RecoveryCodeQuery {
	q.b.OrderByDesc(column)
	return q
}

func (q *RecoveryCodeQuery) Latest(column ...string) *RecoveryCodeQuery {
	q.b.Latest(column...)
	return q
}

func (q *RecoveryCodeQuery) Oldest(column ...string) *RecoveryCodeQuery {
	q.b.Oldest(column...)
	return q
}

func (q *RecoveryCodeQuery) Limit(value int) *RecoveryCodeQuery {
	q.b.Limit(value)
	return q
}

func (q *RecoveryCodeQuery) Offset(value int) *RecoveryCodeQuery {
	q.b.Offset(value)
	return q
}

func (q *RecoveryCodeQuery) ForPage(page, perPage int) *RecoveryCodeQuery {
	q.b.ForPage(page, perPage)
	return q
}

func (q *RecoveryCodeQuery) With(relations ...string) *RecoveryCodeQuery {
	q.b.With(relations...)
	return q
}

func (q *RecoveryCodeQuery) WithCount(relations ...string) *RecoveryCodeQuery {
	q.b.WithCount(relations...)
	return q
}

func (q *RecoveryCodeQuery) WithExists(relation string) *RecoveryCodeQuery {
	q.b.WithExists(relation)
	return q
}

func (q *RecoveryCodeQuery) WithSum(relation, column string) *RecoveryCodeQuery {
	q.b.WithSum(relation, column)
	return q
}

func (q *RecoveryCodeQuery) WithAvg(relation, column string) *RecoveryCodeQuery {
	q.b.WithAvg(relation, column)
	return q
}

func (q *RecoveryCodeQuery) WithMin(relation, column string) *RecoveryCodeQuery {
	q.b.WithMin(relation, column)
	return q
}

func (q *RecoveryCodeQuery) WithMax(relation, column string) *RecoveryCodeQuery {
	q.b.WithMax(relation, column)
	return q
}

func (q *RecoveryCodeQuery) Without(relations ...string) *RecoveryCodeQuery {
	q.b.Without(relations...)
	return q
}

func (q *RecoveryCodeQuery) WithoutGlobalScope(identifier string) *RecoveryCodeQuery {
	q.b.WithoutGlobalScope(identifier)
	return q
}

func (q *RecoveryCodeQuery) WithoutGlobalScopes(identifiers ...string) *RecoveryCodeQuery {
	q.b.WithoutGlobalScopes(identifiers...)
	return q
}

// Get runs the query and returns the rows.
func (q *RecoveryCodeQuery) Get(ctx context.Context, g auth.Grant, columns ...any) (RecoveryCodeCollection, error) {
	rows, err := q.b.Get(ctx, g, columns...)
	return RecoveryCodeCollectionOf(rows), err
}

// First returns the first row, or nil and no error when there is none.
func (q *RecoveryCodeQuery) First(ctx context.Context, g auth.Grant, columns ...any) (*RecoveryCode, error) {
	e, err := q.b.First(ctx, g, columns...)
	return recoveryCodeOf(e), err
}

func (q *RecoveryCodeQuery) FirstOrFail(ctx context.Context, g auth.Grant, columns ...any) (*RecoveryCode, error) {
	e, err := q.b.FirstOrFail(ctx, g, columns...)
	return recoveryCodeOf(e), err
}

func (q *RecoveryCodeQuery) FirstWhere(ctx context.Context, g auth.Grant, column any, args ...any) (*RecoveryCode, error) {
	e, err := q.b.FirstWhere(ctx, g, column, args...)
	return recoveryCodeOf(e), err
}

func (q *RecoveryCodeQuery) FirstOrNew(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*RecoveryCode, error) {
	e, err := q.b.FirstOrNew(ctx, g, attributes, values)
	return recoveryCodeOf(e), err
}

func (q *RecoveryCodeQuery) FirstOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*RecoveryCode, error) {
	e, err := q.b.FirstOrCreate(ctx, g, attributes, values)
	return recoveryCodeOf(e), err
}

func (q *RecoveryCodeQuery) Find(ctx context.Context, g auth.Grant, id any, columns ...any) (*RecoveryCode, error) {
	e, err := q.b.Find(ctx, g, id, columns...)
	return recoveryCodeOf(e), err
}

func (q *RecoveryCodeQuery) FindOrFail(ctx context.Context, g auth.Grant, id any, columns ...any) (*RecoveryCode, error) {
	e, err := q.b.FindOrFail(ctx, g, id, columns...)
	return recoveryCodeOf(e), err
}

func (q *RecoveryCodeQuery) FindOrNew(ctx context.Context, g auth.Grant, id any, columns ...any) (*RecoveryCode, error) {
	e, err := q.b.FindOrNew(ctx, g, id, columns...)
	return recoveryCodeOf(e), err
}

func (q *RecoveryCodeQuery) FindMany(ctx context.Context, g auth.Grant, ids []any, columns ...any) (RecoveryCodeCollection, error) {
	rows, err := q.b.FindMany(ctx, g, ids, columns...)
	return RecoveryCodeCollectionOf(rows), err
}

func (q *RecoveryCodeQuery) Sole(ctx context.Context, g auth.Grant, columns ...any) (*RecoveryCode, error) {
	e, err := q.b.Sole(ctx, g, columns...)
	return recoveryCodeOf(e), err
}

func (q *RecoveryCodeQuery) Create(ctx context.Context, g auth.Grant, attributes map[string]any) (*RecoveryCode, error) {
	e, err := q.b.Create(ctx, g, attributes)
	return recoveryCodeOf(e), err
}

func (q *RecoveryCodeQuery) ForceCreate(ctx context.Context, g auth.Grant, attributes map[string]any) (*RecoveryCode, error) {
	e, err := q.b.ForceCreate(ctx, g, attributes)
	return recoveryCodeOf(e), err
}

func (q *RecoveryCodeQuery) UpdateOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*RecoveryCode, error) {
	e, err := q.b.UpdateOrCreate(ctx, g, attributes, values)
	return recoveryCodeOf(e), err
}

func (q *RecoveryCodeQuery) Paginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (RecoveryCodeCollection, *pagination.LengthAwarePage, error) {
	rows, meta, err := q.b.Paginate(ctx, g, perPage, page, opts, columns...)
	return RecoveryCodeCollectionOf(rows), meta, err
}

func (q *RecoveryCodeQuery) SimplePaginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (RecoveryCodeCollection, *pagination.Page, error) {
	rows, meta, err := q.b.SimplePaginate(ctx, g, perPage, page, opts, columns...)
	return RecoveryCodeCollectionOf(rows), meta, err
}

func (q *RecoveryCodeQuery) CursorPaginate(ctx context.Context, g auth.Grant, perPage int, cursor *pagination.Cursor, opts pagination.Options, columns ...any) (RecoveryCodeCollection, *pagination.CursorPage, error) {
	rows, meta, err := q.b.CursorPaginate(ctx, g, perPage, cursor, opts, columns...)
	return RecoveryCodeCollectionOf(rows), meta, err
}

func (q *RecoveryCodeQuery) Chunk(ctx context.Context, g auth.Grant, count int, callback func(RecoveryCodeCollection, int) (bool, error)) error {
	return q.b.Chunk(ctx, g, count, func(rows model.Rows, page int) (bool, error) {
		return callback(RecoveryCodeCollectionOf(rows), page)
	})
}

func (q *RecoveryCodeQuery) Each(ctx context.Context, g auth.Grant, count int, callback func(*RecoveryCode, int) (bool, error)) error {
	return q.b.Each(ctx, g, count, func(e model.Entity, index int) (bool, error) {
		return callback(recoveryCodeOf(e), index)
	})
}

func (q *RecoveryCodeQuery) Cursor(ctx context.Context, g auth.Grant) iter.Seq2[*RecoveryCode, error] {
	return func(yield func(*RecoveryCode, error) bool) {
		for e, err := range q.b.Cursor(ctx, g) {
			if !yield(recoveryCodeOf(e), err) {
				return
			}
		}
	}
}

func (q *RecoveryCodeQuery) Count(ctx context.Context, g auth.Grant, columns ...any) (int64, error) {
	return q.b.Count(ctx, g, columns...)
}

func (q *RecoveryCodeQuery) Exists(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.Exists(ctx, g)
}

func (q *RecoveryCodeQuery) DoesntExist(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.DoesntExist(ctx, g)
}

func (q *RecoveryCodeQuery) Pluck(ctx context.Context, g auth.Grant, column string) ([]any, error) {
	return q.b.Pluck(ctx, g, column)
}

func (q *RecoveryCodeQuery) Value(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.Value(ctx, g, column)
}

func (q *RecoveryCodeQuery) ValueOrFail(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.ValueOrFail(ctx, g, column)
}

func (q *RecoveryCodeQuery) SoleValue(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.SoleValue(ctx, g, column)
}

func (q *RecoveryCodeQuery) Sum(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Sum(ctx, g, column)
}

func (q *RecoveryCodeQuery) Avg(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Avg(ctx, g, column)
}

func (q *RecoveryCodeQuery) Min(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Min(ctx, g, column)
}

func (q *RecoveryCodeQuery) Max(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Max(ctx, g, column)
}

func (q *RecoveryCodeQuery) Update(ctx context.Context, g auth.Grant, values map[string]any) (int64, error) {
	return q.b.Update(ctx, g, values)
}

func (q *RecoveryCodeQuery) Delete(ctx context.Context, g auth.Grant) (int64, error) {
	return q.b.Delete(ctx, g)
}

func (q *RecoveryCodeQuery) Increment(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Increment(ctx, g, column, amount, extra)
}

func (q *RecoveryCodeQuery) Decrement(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Decrement(ctx, g, column, amount, extra)
}

func (q *RecoveryCodeQuery) Insert(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.Insert(ctx, g, values...)
}

func (q *RecoveryCodeQuery) InsertOrIgnore(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.InsertOrIgnore(ctx, g, values...)
}

func (q *RecoveryCodeQuery) Upsert(ctx context.Context, g auth.Grant, values []map[string]any, uniqueBy, update []string) (int64, error) {
	return q.b.Upsert(ctx, g, values, uniqueBy, update)
}

func (q *RecoveryCodeQuery) Touch(ctx context.Context, g auth.Grant, column ...string) (int64, error) {
	return q.b.Touch(ctx, g, column...)
}

// Rows converts the collection back to the core's rows.
func (c RecoveryCodeCollection) Rows() model.Rows {
	out := make(model.Rows, len(c))
	for i, row := range c {
		out[i] = row
	}
	return out
}

func (c RecoveryCodeCollection) ModelKeys() []any { return c.Rows().ModelKeys() }

func (c RecoveryCodeCollection) Find(key any) *RecoveryCode {
	return recoveryCodeOf(c.Rows().Find(key))
}

func (c RecoveryCodeCollection) FindOrFail(key any) (*RecoveryCode, error) {
	e, err := c.Rows().FindOrFail(key)
	return recoveryCodeOf(e), err
}

func (c RecoveryCodeCollection) Contains(key any) bool { return c.Rows().Contains(key) }

func (c RecoveryCodeCollection) Pluck(column string) []any { return c.Rows().Pluck(column) }

func (c RecoveryCodeCollection) Only(keys ...any) RecoveryCodeCollection {
	return RecoveryCodeCollectionOf(c.Rows().Only(keys...))
}

func (c RecoveryCodeCollection) Except(keys ...any) RecoveryCodeCollection {
	return RecoveryCodeCollectionOf(c.Rows().Except(keys...))
}

func (c RecoveryCodeCollection) Unique() RecoveryCodeCollection {
	return RecoveryCodeCollectionOf(c.Rows().Unique())
}

func (c RecoveryCodeCollection) Load(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().Load(ctx, g, relations...)
}

func (c RecoveryCodeCollection) LoadMissing(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadMissing(ctx, g, relations...)
}

func (c RecoveryCodeCollection) LoadCount(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadCount(ctx, g, relations...)
}

func (c RecoveryCodeCollection) Fresh(ctx context.Context, g auth.Grant, with ...string) (RecoveryCodeCollection, error) {
	rows, err := c.Rows().Fresh(ctx, g, with...)
	return RecoveryCodeCollectionOf(rows), err
}

func (c RecoveryCodeCollection) ToArray() []map[string]any { return c.Rows().ToArray() }

// Fresh reads the row again, as a new RecoveryCode; it shadows the untyped one the
// embedded model promotes.
func (row *RecoveryCode) Fresh(ctx context.Context, g auth.Grant, with ...string) (*RecoveryCode, error) {
	e, err := row.Model.Fresh(ctx, g, with...)
	return recoveryCodeOf(e), err
}

// Replicate returns an unsaved copy of the row without its key; it shadows the
// untyped one the embedded model promotes.
func (row *RecoveryCode) Replicate(except ...string) (*RecoveryCode, error) {
	e, err := row.Model.Replicate(except...)
	return recoveryCodeOf(e), err
}
