// Code generated by aru model:build from TwoFactor.go. DO NOT EDIT.

package models

import (
	"context"
	"iter"

	"github.com/arandu-io/hesape/auth"
	"github.com/arandu-io/hesape/database/model"
	"github.com/arandu-io/hesape/database/query"
	"github.com/arandu-io/hesape/pagination"
)

// TwoFactors starts a query on the table of TwoFactor, through db.
//
// Global scopes are on and, unless the table is Global, every statement is
// filtered by the tenant of the Grant its terminal takes.
func TwoFactors(db model.DB) *TwoFactorQuery { return &TwoFactorQuery{b: twoFactorTable.Query(db)} }

// TwoFactorQuery is a query on the table of TwoFactor.
//
// The methods that build return the query, so they chain. The methods that run
// take a context and an auth.Grant, and return TwoFactor rows or a value; there is
// no way to run one without a Grant.
type TwoFactorQuery struct{ b *model.Builder }

// Base returns the core builder the query forwards to. It is for code in this
// package -- a local scope in the custom block of TwoFactor.go -- and for the
// factory, which builds rows through it.
func (q *TwoFactorQuery) Base() *model.Builder { return q.b }

// New returns an empty TwoFactor on the query's connection, not yet saved, filled
// with what WithAttributes recorded on the query.
func (q *TwoFactorQuery) New() (*TwoFactor, error) {
	e, err := q.b.NewModelInstance(nil)
	return twoFactorOf(e), err
}

// TwoFactorCollection is rows of TwoFactor, as a query returns them.
type TwoFactorCollection []*TwoFactor

// TwoFactorCollectionOf converts rows of the table of TwoFactor. A nil input is a nil
// collection.
func TwoFactorCollectionOf(rows model.Rows) TwoFactorCollection {
	if rows == nil {
		return nil
	}
	out := make(TwoFactorCollection, len(rows))
	for i, e := range rows {
		out[i] = e.(*TwoFactor)
	}
	return out
}

func twoFactorOf(e model.Entity) *TwoFactor {
	row, _ := e.(*TwoFactor)
	return row
}

// twoFactorColumn turns a closure over TwoFactorQuery into one over the core builder, so
// passing func(*TwoFactorQuery) where a column goes adds a parenthesised group.
func twoFactorColumn(column any) any {
	if group, ok := column.(func(*TwoFactorQuery)); ok {
		return func(b *model.Builder) { group(&TwoFactorQuery{b: b}) }
	}
	return column
}

// Clone returns an independent copy of the query.
func (q *TwoFactorQuery) Clone() *TwoFactorQuery { return &TwoFactorQuery{b: q.b.Clone()} }

// Where adds a where clause; a func(*TwoFactorQuery) in place of the column adds a group.
func (q *TwoFactorQuery) Where(column any, args ...any) *TwoFactorQuery {
	q.b.Where(twoFactorColumn(column), args...)
	return q
}

// OrWhere adds an or-where clause; a func(*TwoFactorQuery) in place of the column adds a group.
func (q *TwoFactorQuery) OrWhere(column any, args ...any) *TwoFactorQuery {
	q.b.OrWhere(twoFactorColumn(column), args...)
	return q
}

// WhereNot adds a negated where clause, or a negated group.
func (q *TwoFactorQuery) WhereNot(column any, args ...any) *TwoFactorQuery {
	q.b.WhereNot(twoFactorColumn(column), args...)
	return q
}

// OrWhereNot adds an or-joined negated where clause, or a negated group.
func (q *TwoFactorQuery) OrWhereNot(column any, args ...any) *TwoFactorQuery {
	q.b.OrWhereNot(twoFactorColumn(column), args...)
	return q
}

func (q *TwoFactorQuery) WhereIn(column any, values []any) *TwoFactorQuery {
	q.b.WhereIn(column, values)
	return q
}

func (q *TwoFactorQuery) WhereNotIn(column any, values []any) *TwoFactorQuery {
	q.b.WhereNotIn(column, values)
	return q
}

func (q *TwoFactorQuery) WhereNull(columns ...any) *TwoFactorQuery {
	q.b.WhereNull(columns...)
	return q
}

func (q *TwoFactorQuery) WhereNotNull(columns ...any) *TwoFactorQuery {
	q.b.WhereNotNull(columns...)
	return q
}

func (q *TwoFactorQuery) WhereBetween(column any, from, to any) *TwoFactorQuery {
	q.b.WhereBetween(column, from, to)
	return q
}

func (q *TwoFactorQuery) WhereColumn(first any, args ...any) *TwoFactorQuery {
	q.b.WhereColumn(first, args...)
	return q
}

func (q *TwoFactorQuery) WhereKey(id any) *TwoFactorQuery {
	q.b.WhereKey(id)
	return q
}

func (q *TwoFactorQuery) WhereExists(callback func(*query.Builder)) *TwoFactorQuery {
	q.b.WhereExists(callback)
	return q
}

func (q *TwoFactorQuery) WhereNotExists(callback func(*query.Builder)) *TwoFactorQuery {
	q.b.WhereNotExists(callback)
	return q
}

func (q *TwoFactorQuery) WhereHas(relation string, callback func(*query.Builder)) *TwoFactorQuery {
	q.b.WhereHas(relation, callback)
	return q
}

func (q *TwoFactorQuery) OrWhereHas(relation string, callback func(*query.Builder)) *TwoFactorQuery {
	q.b.OrWhereHas(relation, callback)
	return q
}

func (q *TwoFactorQuery) WhereDoesntHave(relation string, callback func(*query.Builder)) *TwoFactorQuery {
	q.b.WhereDoesntHave(relation, callback)
	return q
}

func (q *TwoFactorQuery) OrWhereDoesntHave(relation string, callback func(*query.Builder)) *TwoFactorQuery {
	q.b.OrWhereDoesntHave(relation, callback)
	return q
}

func (q *TwoFactorQuery) WhereRelation(relation string, column any, args ...any) *TwoFactorQuery {
	q.b.WhereRelation(relation, column, args...)
	return q
}

func (q *TwoFactorQuery) OrWhereRelation(relation string, column any, args ...any) *TwoFactorQuery {
	q.b.OrWhereRelation(relation, column, args...)
	return q
}

func (q *TwoFactorQuery) WhereHasCount(relation string, callback func(*query.Builder), operator string, count int) *TwoFactorQuery {
	q.b.WhereHasCount(relation, callback, operator, count)
	return q
}

func (q *TwoFactorQuery) WhereBelongsTo(relationshipName string, related ...model.Entity) *TwoFactorQuery {
	q.b.WhereBelongsTo(relationshipName, related...)
	return q
}

func (q *TwoFactorQuery) Has(relation, operator string, count int, boolean string, callback func(*query.Builder)) *TwoFactorQuery {
	q.b.Has(relation, operator, count, boolean, callback)
	return q
}

func (q *TwoFactorQuery) OrHas(relation, operator string, count int) *TwoFactorQuery {
	q.b.OrHas(relation, operator, count)
	return q
}

func (q *TwoFactorQuery) DoesntHave(relation, boolean string, callback func(*query.Builder)) *TwoFactorQuery {
	q.b.DoesntHave(relation, boolean, callback)
	return q
}

func (q *TwoFactorQuery) OrDoesntHave(relation string) *TwoFactorQuery {
	q.b.OrDoesntHave(relation)
	return q
}

func (q *TwoFactorQuery) Select(columns ...any) *TwoFactorQuery {
	q.b.Select(columns...)
	return q
}

func (q *TwoFactorQuery) AddSelect(columns ...any) *TwoFactorQuery {
	q.b.AddSelect(columns...)
	return q
}

func (q *TwoFactorQuery) SelectRaw(expression string, bindings ...any) *TwoFactorQuery {
	q.b.SelectRaw(expression, bindings...)
	return q
}

func (q *TwoFactorQuery) Join(table any, first any, args ...any) *TwoFactorQuery {
	q.b.Join(table, first, args...)
	return q
}

func (q *TwoFactorQuery) GroupBy(groups ...any) *TwoFactorQuery {
	q.b.GroupBy(groups...)
	return q
}

func (q *TwoFactorQuery) OrderBy(column any, direction ...string) *TwoFactorQuery {
	q.b.OrderBy(column, direction...)
	return q
}

func (q *TwoFactorQuery) OrderByDesc(column any) *TwoFactorQuery {
	q.b.OrderByDesc(column)
	return q
}

func (q *TwoFactorQuery) Latest(column ...string) *TwoFactorQuery {
	q.b.Latest(column...)
	return q
}

func (q *TwoFactorQuery) Oldest(column ...string) *TwoFactorQuery {
	q.b.Oldest(column...)
	return q
}

func (q *TwoFactorQuery) Limit(value int) *TwoFactorQuery {
	q.b.Limit(value)
	return q
}

func (q *TwoFactorQuery) Offset(value int) *TwoFactorQuery {
	q.b.Offset(value)
	return q
}

func (q *TwoFactorQuery) ForPage(page, perPage int) *TwoFactorQuery {
	q.b.ForPage(page, perPage)
	return q
}

func (q *TwoFactorQuery) With(relations ...string) *TwoFactorQuery {
	q.b.With(relations...)
	return q
}

func (q *TwoFactorQuery) WithCount(relations ...string) *TwoFactorQuery {
	q.b.WithCount(relations...)
	return q
}

func (q *TwoFactorQuery) WithExists(relation string) *TwoFactorQuery {
	q.b.WithExists(relation)
	return q
}

func (q *TwoFactorQuery) WithSum(relation, column string) *TwoFactorQuery {
	q.b.WithSum(relation, column)
	return q
}

func (q *TwoFactorQuery) WithAvg(relation, column string) *TwoFactorQuery {
	q.b.WithAvg(relation, column)
	return q
}

func (q *TwoFactorQuery) WithMin(relation, column string) *TwoFactorQuery {
	q.b.WithMin(relation, column)
	return q
}

func (q *TwoFactorQuery) WithMax(relation, column string) *TwoFactorQuery {
	q.b.WithMax(relation, column)
	return q
}

func (q *TwoFactorQuery) Without(relations ...string) *TwoFactorQuery {
	q.b.Without(relations...)
	return q
}

func (q *TwoFactorQuery) WithoutGlobalScope(identifier string) *TwoFactorQuery {
	q.b.WithoutGlobalScope(identifier)
	return q
}

func (q *TwoFactorQuery) WithoutGlobalScopes(identifiers ...string) *TwoFactorQuery {
	q.b.WithoutGlobalScopes(identifiers...)
	return q
}

// Get runs the query and returns the rows.
func (q *TwoFactorQuery) Get(ctx context.Context, g auth.Grant, columns ...any) (TwoFactorCollection, error) {
	rows, err := q.b.Get(ctx, g, columns...)
	return TwoFactorCollectionOf(rows), err
}

// First returns the first row, or nil and no error when there is none.
func (q *TwoFactorQuery) First(ctx context.Context, g auth.Grant, columns ...any) (*TwoFactor, error) {
	e, err := q.b.First(ctx, g, columns...)
	return twoFactorOf(e), err
}

func (q *TwoFactorQuery) FirstOrFail(ctx context.Context, g auth.Grant, columns ...any) (*TwoFactor, error) {
	e, err := q.b.FirstOrFail(ctx, g, columns...)
	return twoFactorOf(e), err
}

func (q *TwoFactorQuery) FirstWhere(ctx context.Context, g auth.Grant, column any, args ...any) (*TwoFactor, error) {
	e, err := q.b.FirstWhere(ctx, g, column, args...)
	return twoFactorOf(e), err
}

func (q *TwoFactorQuery) FirstOrNew(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*TwoFactor, error) {
	e, err := q.b.FirstOrNew(ctx, g, attributes, values)
	return twoFactorOf(e), err
}

func (q *TwoFactorQuery) FirstOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*TwoFactor, error) {
	e, err := q.b.FirstOrCreate(ctx, g, attributes, values)
	return twoFactorOf(e), err
}

func (q *TwoFactorQuery) Find(ctx context.Context, g auth.Grant, id any, columns ...any) (*TwoFactor, error) {
	e, err := q.b.Find(ctx, g, id, columns...)
	return twoFactorOf(e), err
}

func (q *TwoFactorQuery) FindOrFail(ctx context.Context, g auth.Grant, id any, columns ...any) (*TwoFactor, error) {
	e, err := q.b.FindOrFail(ctx, g, id, columns...)
	return twoFactorOf(e), err
}

func (q *TwoFactorQuery) FindOrNew(ctx context.Context, g auth.Grant, id any, columns ...any) (*TwoFactor, error) {
	e, err := q.b.FindOrNew(ctx, g, id, columns...)
	return twoFactorOf(e), err
}

func (q *TwoFactorQuery) FindMany(ctx context.Context, g auth.Grant, ids []any, columns ...any) (TwoFactorCollection, error) {
	rows, err := q.b.FindMany(ctx, g, ids, columns...)
	return TwoFactorCollectionOf(rows), err
}

func (q *TwoFactorQuery) Sole(ctx context.Context, g auth.Grant, columns ...any) (*TwoFactor, error) {
	e, err := q.b.Sole(ctx, g, columns...)
	return twoFactorOf(e), err
}

func (q *TwoFactorQuery) Create(ctx context.Context, g auth.Grant, attributes map[string]any) (*TwoFactor, error) {
	e, err := q.b.Create(ctx, g, attributes)
	return twoFactorOf(e), err
}

func (q *TwoFactorQuery) ForceCreate(ctx context.Context, g auth.Grant, attributes map[string]any) (*TwoFactor, error) {
	e, err := q.b.ForceCreate(ctx, g, attributes)
	return twoFactorOf(e), err
}

func (q *TwoFactorQuery) UpdateOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*TwoFactor, error) {
	e, err := q.b.UpdateOrCreate(ctx, g, attributes, values)
	return twoFactorOf(e), err
}

func (q *TwoFactorQuery) Paginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (TwoFactorCollection, *pagination.LengthAwarePage, error) {
	rows, meta, err := q.b.Paginate(ctx, g, perPage, page, opts, columns...)
	return TwoFactorCollectionOf(rows), meta, err
}

func (q *TwoFactorQuery) SimplePaginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (TwoFactorCollection, *pagination.Page, error) {
	rows, meta, err := q.b.SimplePaginate(ctx, g, perPage, page, opts, columns...)
	return TwoFactorCollectionOf(rows), meta, err
}

func (q *TwoFactorQuery) CursorPaginate(ctx context.Context, g auth.Grant, perPage int, cursor *pagination.Cursor, opts pagination.Options, columns ...any) (TwoFactorCollection, *pagination.CursorPage, error) {
	rows, meta, err := q.b.CursorPaginate(ctx, g, perPage, cursor, opts, columns...)
	return TwoFactorCollectionOf(rows), meta, err
}

func (q *TwoFactorQuery) Chunk(ctx context.Context, g auth.Grant, count int, callback func(TwoFactorCollection, int) (bool, error)) error {
	return q.b.Chunk(ctx, g, count, func(rows model.Rows, page int) (bool, error) {
		return callback(TwoFactorCollectionOf(rows), page)
	})
}

func (q *TwoFactorQuery) Each(ctx context.Context, g auth.Grant, count int, callback func(*TwoFactor, int) (bool, error)) error {
	return q.b.Each(ctx, g, count, func(e model.Entity, index int) (bool, error) {
		return callback(twoFactorOf(e), index)
	})
}

func (q *TwoFactorQuery) Cursor(ctx context.Context, g auth.Grant) iter.Seq2[*TwoFactor, error] {
	return func(yield func(*TwoFactor, error) bool) {
		for e, err := range q.b.Cursor(ctx, g) {
			if !yield(twoFactorOf(e), err) {
				return
			}
		}
	}
}

func (q *TwoFactorQuery) Count(ctx context.Context, g auth.Grant, columns ...any) (int64, error) {
	return q.b.Count(ctx, g, columns...)
}

func (q *TwoFactorQuery) Exists(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.Exists(ctx, g)
}

func (q *TwoFactorQuery) DoesntExist(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.DoesntExist(ctx, g)
}

func (q *TwoFactorQuery) Pluck(ctx context.Context, g auth.Grant, column string) ([]any, error) {
	return q.b.Pluck(ctx, g, column)
}

func (q *TwoFactorQuery) Value(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.Value(ctx, g, column)
}

func (q *TwoFactorQuery) ValueOrFail(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.ValueOrFail(ctx, g, column)
}

func (q *TwoFactorQuery) SoleValue(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.SoleValue(ctx, g, column)
}

func (q *TwoFactorQuery) Sum(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Sum(ctx, g, column)
}

func (q *TwoFactorQuery) Avg(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Avg(ctx, g, column)
}

func (q *TwoFactorQuery) Min(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Min(ctx, g, column)
}

func (q *TwoFactorQuery) Max(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Max(ctx, g, column)
}

func (q *TwoFactorQuery) Update(ctx context.Context, g auth.Grant, values map[string]any) (int64, error) {
	return q.b.Update(ctx, g, values)
}

func (q *TwoFactorQuery) Delete(ctx context.Context, g auth.Grant) (int64, error) {
	return q.b.Delete(ctx, g)
}

func (q *TwoFactorQuery) Increment(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Increment(ctx, g, column, amount, extra)
}

func (q *TwoFactorQuery) Decrement(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Decrement(ctx, g, column, amount, extra)
}

func (q *TwoFactorQuery) Insert(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.Insert(ctx, g, values...)
}

func (q *TwoFactorQuery) InsertOrIgnore(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.InsertOrIgnore(ctx, g, values...)
}

func (q *TwoFactorQuery) Upsert(ctx context.Context, g auth.Grant, values []map[string]any, uniqueBy, update []string) (int64, error) {
	return q.b.Upsert(ctx, g, values, uniqueBy, update)
}

func (q *TwoFactorQuery) Touch(ctx context.Context, g auth.Grant, column ...string) (int64, error) {
	return q.b.Touch(ctx, g, column...)
}

// Rows converts the collection back to the core's rows.
func (c TwoFactorCollection) Rows() model.Rows {
	out := make(model.Rows, len(c))
	for i, row := range c {
		out[i] = row
	}
	return out
}

func (c TwoFactorCollection) ModelKeys() []any { return c.Rows().ModelKeys() }

func (c TwoFactorCollection) Find(key any) *TwoFactor { return twoFactorOf(c.Rows().Find(key)) }

func (c TwoFactorCollection) FindOrFail(key any) (*TwoFactor, error) {
	e, err := c.Rows().FindOrFail(key)
	return twoFactorOf(e), err
}

func (c TwoFactorCollection) Contains(key any) bool { return c.Rows().Contains(key) }

func (c TwoFactorCollection) Pluck(column string) []any { return c.Rows().Pluck(column) }

func (c TwoFactorCollection) Only(keys ...any) TwoFactorCollection {
	return TwoFactorCollectionOf(c.Rows().Only(keys...))
}

func (c TwoFactorCollection) Except(keys ...any) TwoFactorCollection {
	return TwoFactorCollectionOf(c.Rows().Except(keys...))
}

func (c TwoFactorCollection) Unique() TwoFactorCollection {
	return TwoFactorCollectionOf(c.Rows().Unique())
}

func (c TwoFactorCollection) Load(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().Load(ctx, g, relations...)
}

func (c TwoFactorCollection) LoadMissing(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadMissing(ctx, g, relations...)
}

func (c TwoFactorCollection) LoadCount(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadCount(ctx, g, relations...)
}

func (c TwoFactorCollection) Fresh(ctx context.Context, g auth.Grant, with ...string) (TwoFactorCollection, error) {
	rows, err := c.Rows().Fresh(ctx, g, with...)
	return TwoFactorCollectionOf(rows), err
}

func (c TwoFactorCollection) ToArray() []map[string]any { return c.Rows().ToArray() }

// Fresh reads the row again, as a new TwoFactor; it shadows the untyped one the
// embedded model promotes.
func (row *TwoFactor) Fresh(ctx context.Context, g auth.Grant, with ...string) (*TwoFactor, error) {
	e, err := row.Model.Fresh(ctx, g, with...)
	return twoFactorOf(e), err
}

// Replicate returns an unsaved copy of the row without its key; it shadows the
// untyped one the embedded model promotes.
func (row *TwoFactor) Replicate(except ...string) (*TwoFactor, error) {
	e, err := row.Model.Replicate(except...)
	return twoFactorOf(e), err
}
