// Code generated by `aru view:build` from app.kyse.go. DO NOT EDIT.
//
// Edit the .kyse.go and run `aru view:build`. Changes here are overwritten.

package layouts

import (
	"html/template"
	"io"

	"github.com/arandu-io/framework/view"
	"github.com/arandu-io/kyse/components"
)

func init() { view.RegisterLayout("layouts.app", renderLayoutsApp) }

// renderLayoutsApp renders the layouts.app layout.
func renderLayoutsApp(w io.Writer, data any, sections map[string]func(io.Writer) error) error {
	d, ok := data.(view.Layout)
	if !ok {
		return view.WrongData("layouts.app", "view.Layout", data)
	}
	_ = d
	var err error
	if err == nil {
		_, err = io.WriteString(w, "<!doctype html>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<html lang=\"en\" class=\"h-full\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<head>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<meta charset=\"utf-8\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<title>")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:18
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.PageTitle())))
//line resources/views/layouts/app.go:47
	}
	if err == nil {
		_, err = io.WriteString(w, "</title>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<link rel=\"icon\" href=\"/favicon.ico\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<!-- What a page says about itself. Each one is written only when the page\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t     filled it in: an empty description is worse than none, because a search\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t     engine that finds one stops looking for a better sentence in the body. -->\n")
	}
//line resources/views/layouts/app.kyse.go:24
	if d.PageDescription() != "" {
//line resources/views/layouts/app.go:66
		if err == nil {
			_, err = io.WriteString(w, "\t\t<meta name=\"description\" content=\"")
		}
		if err == nil {
//line resources/views/layouts/app.kyse.go:25
			_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.PageDescription())))
//line resources/views/layouts/app.go:73
		}
		if err == nil {
			_, err = io.WriteString(w, "\">\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t<meta property=\"og:description\" content=\"")
		}
		if err == nil {
//line resources/views/layouts/app.kyse.go:26
			_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.PageDescription())))
//line resources/views/layouts/app.go:84
		}
		if err == nil {
			_, err = io.WriteString(w, "\">\n")
		}
	}
//line resources/views/layouts/app.kyse.go:28
	if d.CanonicalURL() != "" {
//line resources/views/layouts/app.go:92
		if err == nil {
			_, err = io.WriteString(w, "\t\t<link rel=\"canonical\" href=\"")
		}
		if err == nil {
//line resources/views/layouts/app.kyse.go:29
			_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.CanonicalURL())))
//line resources/views/layouts/app.go:99
		}
		if err == nil {
			_, err = io.WriteString(w, "\">\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t<meta property=\"og:url\" content=\"")
		}
		if err == nil {
//line resources/views/layouts/app.kyse.go:30
			_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.CanonicalURL())))
//line resources/views/layouts/app.go:110
		}
		if err == nil {
			_, err = io.WriteString(w, "\">\n")
		}
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<meta property=\"og:title\" content=\"")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:32
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.PageTitle())))
//line resources/views/layouts/app.go:122
	}
	if err == nil {
		_, err = io.WriteString(w, "\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<meta property=\"og:site_name\" content=\"")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:33
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.BrandName())))
//line resources/views/layouts/app.go:133
	}
	if err == nil {
		_, err = io.WriteString(w, "\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<meta property=\"og:type\" content=\"website\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<meta name=\"twitter:card\" content=\"summary_large_image\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<!-- Every asset is embedded in the binary and addressed by content hash. No\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t     CDN, because the CSP is script-src 'self'; no build directory, because\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t     there is no bundler to write one (RULE 13). -->\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<link rel=\"stylesheet\" href=\"")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:40
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(view.URL("app.css"))))
//line resources/views/layouts/app.go:159
	}
	if err == nil {
		_, err = io.WriteString(w, "\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<script src=\"")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:41
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(view.URL("htmx.min.js"))))
//line resources/views/layouts/app.go:170
	}
	if err == nil {
		_, err = io.WriteString(w, "\" defer></script>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<script src=\"")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:42
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(view.URL("alpine.min.js"))))
//line resources/views/layouts/app.go:181
	}
	if err == nil {
		_, err = io.WriteString(w, "\" defer></script>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<script src=\"")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:43
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(view.URL("basecoat.bundle.js"))))
//line resources/views/layouts/app.go:192
	}
	if err == nil {
		_, err = io.WriteString(w, "\" defer></script>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<!-- The theme is read before the first paint, so a person who chose dark does\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t     not get a white flash on every navigation. It is the one piece of script\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t     that cannot wait for Alpine, and it is four lines. -->\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<script src=\"")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:48
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(view.URL("theme.js"))))
//line resources/views/layouts/app.go:212
	}
	if err == nil {
		_, err = io.WriteString(w, "\"></script>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "</head>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<!-- hx-headers is load-bearing: without it every hx-post fails the CSRF check,\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "     and the failure reads like a broken session rather than a missing attribute. -->\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "<body hx-boost=\"true\" hx-headers='{\"X-CSRF-Token\": \"")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:52
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.CSRFToken())))
//line resources/views/layouts/app.go:232
	}
	if err == nil {
		_, err = io.WriteString(w, "\"}' class=\"bg-background text-foreground min-h-full antialiased\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t<div class=\"mx-auto flex min-h-full w-full max-w-3xl flex-col px-6\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t<header class=\"flex items-center justify-between border-b py-6\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t\t<a class=\"text-sm font-semibold tracking-tight\" href=\"")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:55
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.HomeLink())))
//line resources/views/layouts/app.go:249
	}
	if err == nil {
		_, err = io.WriteString(w, "\">")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:55
		_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.BrandName())))
//line resources/views/layouts/app.go:257
	}
	if err == nil {
		_, err = io.WriteString(w, "</a>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t\t<nav class=\"flex items-center gap-3 text-sm\">\n")
	}
	if err == nil {
//line resources/views/layouts/app.kyse.go:57
		_, err = io.WriteString(w, view.Text(components.ThemeToggle()))
//line resources/views/layouts/app.go:268
	}
//line resources/views/layouts/app.kyse.go:58
	if !d.SignedIn() {
//line resources/views/layouts/app.go:272
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t\t\t<a class=\"btn\" data-variant=\"ghost\" data-size=\"sm\" href=\"")
		}
		if err == nil {
//line resources/views/layouts/app.kyse.go:59
			_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.LoginLink())))
//line resources/views/layouts/app.go:279
		}
		if err == nil {
			_, err = io.WriteString(w, "\">Sign in</a>\n")
		}
//line resources/views/layouts/app.kyse.go:60
		if d.RegisterLink() != "" {
//line resources/views/layouts/app.go:286
			if err == nil {
				_, err = io.WriteString(w, "\t\t\t\t\t\t<a class=\"btn\" data-size=\"sm\" href=\"")
			}
			if err == nil {
//line resources/views/layouts/app.kyse.go:61
				_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.RegisterLink())))
//line resources/views/layouts/app.go:293
			}
			if err == nil {
				_, err = io.WriteString(w, "\">Register</a>\n")
			}
		}
	}
//line resources/views/layouts/app.kyse.go:64
	if d.SignedIn() {
//line resources/views/layouts/app.go:302
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t\t\t<span class=\"text-muted-foreground\">")
		}
		if err == nil {
//line resources/views/layouts/app.kyse.go:65
			_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.SignedInName())))
//line resources/views/layouts/app.go:309
		}
		if err == nil {
			_, err = io.WriteString(w, "</span>\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t\t\t<form method=\"post\" action=\"")
		}
		if err == nil {
//line resources/views/layouts/app.kyse.go:66
			_, err = io.WriteString(w, template.HTMLEscapeString(view.Text(d.LogoutLink())))
//line resources/views/layouts/app.go:320
		}
		if err == nil {
			_, err = io.WriteString(w, "\">\n")
		}
		if err == nil {
			err = view.CSRF(w, data)
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t\t\t\t<button class=\"btn\" data-variant=\"ghost\" data-size=\"sm\" type=\"submit\">Sign out</button>\n")
		}
		if err == nil {
			_, err = io.WriteString(w, "\t\t\t\t\t</form>\n")
		}
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t\t</nav>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t</header>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t<main class=\"flex-1 py-12\">\n")
	}
	if err == nil {
		err = view.Yield(w, sections, "content")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t</main>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t<!-- The tray flash messages land in. An endpoint that saves something answers\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t     with a toast fragment and hx-swap=\"beforeend\" on this element; the vendored\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t     script arms whatever appears inside it. Empty until then, and it costs one\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t     element to never write the \"do I have a message\" branch again. -->\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t<div id=\"toaster\" class=\"toaster\" aria-live=\"polite\"></div>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t<!-- One @yield, and it is 'content'. A section only one layout yields is a\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t     section that disappears without a word when the layout is replaced. -->\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t<footer class=\"text-muted-foreground border-t py-6 text-sm\">\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t\t<p>Built with Arandu.</p>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t\t</footer>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "\t</div>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "</body>\n")
	}
	if err == nil {
		_, err = io.WriteString(w, "</html>\n")
	}
	return err
}

var (
	_ = template.HTMLEscapeString
	_ = io.WriteString
	_ = view.Text
)
